-- schema.sql — consolidated snapshot of the cumulative control-plane schema.
--
-- Generated by applying migrations V002..V041 (the full chain ported from
-- crates/networker-dashboard/src/db/migrations.rs, including the V025 code
-- migration) to a fresh PostgreSQL 16 and running:
--
--   pg_dump --schema-only --no-owner --no-privileges
--
-- This file is REFERENCE ONLY — the source of truth is the ordered scripts
-- in this directory, applied by SchemaMigrator. Do NOT apply this file to a
-- database SchemaMigrator manages: it has no _migrations rows, so the
-- migrator would try to replay the chain. Regenerate it whenever a new
-- migration lands (see docs/schema-ownership.md).
--
-- V001 (TestRun/RequestAttempt/DnsResult/... probe-result tables) is owned by
-- the networker-tester crate and is NOT part of this snapshot.

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._migrations (
    version integer NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: agent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent (
    agent_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    region character varying(100),
    provider character varying(20),
    status character varying(20) DEFAULT 'offline'::character varying NOT NULL,
    version character varying(50),
    os character varying(50),
    arch character varying(20),
    last_heartbeat timestamp with time zone,
    registered_at timestamp with time zone DEFAULT now() NOT NULL,
    api_key character varying(255) NOT NULL,
    tags jsonb,
    project_id character(14) NOT NULL,
    tester_id uuid,
    api_key_hash character varying(64)
);


--
-- Name: agent_command; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_command (
    command_id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_id uuid NOT NULL,
    config_id uuid,
    verb text NOT NULL,
    args jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    result jsonb,
    error_message text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone
);


--
-- Name: alert_channel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_channel (
    channel_id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT alert_channel_kind_check CHECK ((kind = ANY (ARRAY['webhook'::text, 'email'::text])))
);


--
-- Name: alert_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_event (
    event_id uuid DEFAULT gen_random_uuid() NOT NULL,
    rule_id uuid NOT NULL,
    run_id uuid NOT NULL,
    fired_at timestamp with time zone DEFAULT now() NOT NULL,
    state text NOT NULL,
    value double precision,
    message text,
    delivery_status text,
    CONSTRAINT alert_event_state_check CHECK ((state = ANY (ARRAY['firing'::text, 'resolved'::text])))
);


--
-- Name: alert_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_rule (
    rule_id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    test_config_id uuid,
    metric text NOT NULL,
    comparator text NOT NULL,
    threshold double precision NOT NULL,
    window_runs integer DEFAULT 1 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    channel_id uuid NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT alert_rule_comparator_check CHECK ((comparator = ANY (ARRAY['gt'::text, 'lt'::text]))),
    CONSTRAINT alert_rule_metric_check CHECK ((metric = ANY (ARRAY['p95_ms'::text, 'mean_ms'::text, 'error_rate'::text, 'success_rate'::text]))),
    CONSTRAINT alert_rule_window_runs_check CHECK (((window_runs >= 1) AND (window_runs <= 50)))
);


--
-- Name: benchmark_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.benchmark_artifact (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    test_run_id uuid NOT NULL,
    environment jsonb NOT NULL,
    methodology jsonb NOT NULL,
    launches jsonb NOT NULL,
    cases jsonb NOT NULL,
    samples jsonb,
    summaries jsonb NOT NULL,
    data_quality jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: benchmark_testbed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.benchmark_testbed (
    testbed_id uuid NOT NULL,
    config_id uuid NOT NULL,
    cloud character varying(20) NOT NULL,
    region character varying(100) NOT NULL,
    topology character varying(20) DEFAULT 'loopback'::character varying NOT NULL,
    endpoint_vm_id character varying(200),
    tester_vm_id character varying(200),
    endpoint_ip character varying(200),
    tester_ip character varying(200),
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    languages jsonb DEFAULT '[]'::jsonb NOT NULL,
    vm_size character varying(100),
    os text DEFAULT 'linux'::text NOT NULL,
    proxies jsonb DEFAULT '[]'::jsonb NOT NULL,
    tester_os text DEFAULT 'server'::text NOT NULL
);


--
-- Name: benchmark_vm_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.benchmark_vm_catalog (
    vm_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    cloud character varying(20) NOT NULL,
    region character varying(100) NOT NULL,
    ip character varying(200) NOT NULL,
    ssh_user character varying(100) DEFAULT 'azureuser'::character varying NOT NULL,
    languages jsonb DEFAULT '[]'::jsonb NOT NULL,
    vm_size character varying(100),
    status character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    last_health_check timestamp with time zone,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    project_id character(14) NOT NULL
);


--
-- Name: cloud_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cloud_account (
    account_id uuid NOT NULL,
    owner_id uuid,
    name character varying(200) NOT NULL,
    provider character varying(20) NOT NULL,
    credentials_enc bytea NOT NULL,
    credentials_nonce bytea NOT NULL,
    region_default character varying(100),
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    last_validated timestamp with time zone,
    validation_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    project_id character(14) NOT NULL
);


--
-- Name: cloud_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cloud_connection (
    connection_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    provider character varying(20) NOT NULL,
    config jsonb NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    last_validated timestamp with time zone,
    validation_error text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    project_id character(14)
);


--
-- Name: command_approval; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.command_approval (
    approval_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    command_type character varying(50) NOT NULL,
    command_detail jsonb NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    requested_by uuid NOT NULL,
    decided_by uuid,
    requested_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    reason text,
    project_id character(14) NOT NULL
);


--
-- Name: comparison_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comparison_group (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    base_workload jsonb NOT NULL,
    methodology jsonb,
    cells jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT comparison_group_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text])))
);


--
-- Name: cost_rate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cost_rate (
    cost_rate_id uuid DEFAULT gen_random_uuid() NOT NULL,
    cloud text NOT NULL,
    vm_size text NOT NULL,
    region text,
    rate_per_hour_usd numeric(12,6) NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    source text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT cost_rate_cloud_valid CHECK ((cloud = ANY (ARRAY['aws'::text, 'azure'::text, 'gcp'::text]))),
    CONSTRAINT cost_rate_rate_non_negative CHECK ((rate_per_hour_usd >= (0)::numeric)),
    CONSTRAINT cost_rate_window_ordered CHECK (((effective_to IS NULL) OR (effective_to > effective_from)))
);


--
-- Name: dash_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dash_user (
    user_id uuid NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    role character varying(20) DEFAULT 'viewer'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone,
    must_change_password boolean DEFAULT false NOT NULL,
    password_reset_token character varying(128),
    password_reset_expires timestamp with time zone,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    auth_provider character varying(20) DEFAULT 'local'::character varying NOT NULL,
    sso_subject_id character varying(255),
    display_name character varying(200),
    avatar_url text,
    sso_only boolean DEFAULT false NOT NULL,
    is_platform_admin boolean DEFAULT false NOT NULL
);


--
-- Name: deployment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deployment (
    deployment_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    config jsonb NOT NULL,
    provider_summary text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    endpoint_ips jsonb,
    agent_id uuid,
    error_message text,
    log text,
    cloud_account_id uuid,
    project_id character(14) NOT NULL
);


--
-- Name: migration_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migration_audit_log (
    log_id uuid DEFAULT gen_random_uuid() NOT NULL,
    request_id uuid NOT NULL,
    step character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    details jsonb,
    checksum character varying(128),
    duration_ms bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: migration_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migration_request (
    request_id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id character(14) NOT NULL,
    from_zone character(2) NOT NULL,
    to_zone character(2) NOT NULL,
    reason text NOT NULL,
    requested_by uuid NOT NULL,
    approved_by uuid,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    scheduled_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    data_size_mb bigint,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: perf_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perf_log (
    id bigint NOT NULL,
    logged_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid,
    session_id character varying(64),
    kind character varying(10) NOT NULL,
    method character varying(10),
    path character varying(500),
    status smallint,
    total_ms real,
    server_ms real,
    network_ms real,
    source character varying(10),
    component character varying(100),
    trigger character varying(100),
    render_ms real,
    item_count integer,
    meta jsonb
);


--
-- Name: perf_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.perf_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: perf_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.perf_log_id_seq OWNED BY public.perf_log.id;


--
-- Name: project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project (
    name character varying(200) NOT NULL,
    slug character varying(100) NOT NULL,
    description text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    deleted_at timestamp with time zone,
    delete_protection boolean DEFAULT false NOT NULL,
    project_id character(14) NOT NULL
);


--
-- Name: project_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_member (
    user_id uuid NOT NULL,
    role character varying(20) DEFAULT 'viewer'::character varying NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    invited_by uuid,
    project_id character(14) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    invite_sent_at timestamp with time zone
);


--
-- Name: project_routing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_routing (
    project_id character(14) NOT NULL,
    home_zone character(2) NOT NULL,
    current_zone character(2) NOT NULL,
    migrated_at timestamp with time zone,
    migrated_by uuid
);


--
-- Name: project_tester; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_tester (
    tester_id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    cloud text NOT NULL,
    region text NOT NULL,
    vm_size text DEFAULT 'Standard_D2s_v3'::text NOT NULL,
    vm_name text,
    vm_resource_id text,
    public_ip inet,
    ssh_user text DEFAULT 'azureuser'::text NOT NULL,
    power_state text DEFAULT 'provisioning'::text NOT NULL,
    allocation text DEFAULT 'idle'::text NOT NULL,
    status_message text,
    locked_by_config_id uuid,
    installer_version text,
    last_installed_at timestamp with time zone,
    auto_shutdown_enabled boolean DEFAULT true NOT NULL,
    auto_shutdown_local_hour smallint DEFAULT 23 NOT NULL,
    next_shutdown_at timestamp with time zone,
    shutdown_deferral_count smallint DEFAULT 0 NOT NULL,
    auto_probe_enabled boolean DEFAULT false NOT NULL,
    last_used_at timestamp with time zone,
    avg_benchmark_duration_seconds integer,
    benchmark_run_count integer DEFAULT 0 NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    cloud_connection_id uuid,
    requested_os character varying(50) DEFAULT 'ubuntu-24.04'::character varying,
    requested_variant character varying(20) DEFAULT 'server'::character varying,
    os_distro character varying(50),
    os_version character varying(50),
    os_variant character varying(20),
    os_arch character varying(20),
    os_kernel character varying(100),
    cloud_account_id uuid,
    CONSTRAINT lock_holder_implies_locked CHECK ((((allocation = 'locked'::text) AND (locked_by_config_id IS NOT NULL)) OR ((allocation <> 'locked'::text) AND (locked_by_config_id IS NULL)))),
    CONSTRAINT lock_requires_running_vm CHECK (((allocation <> 'locked'::text) OR (power_state = 'running'::text)))
);


--
-- Name: server_registry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.server_registry (
    server_id character(3) NOT NULL,
    zone_code character(2) NOT NULL,
    hostname character varying(255) NOT NULL,
    endpoint character varying(255) NOT NULL,
    internal_ip character varying(45),
    db_url character varying(500),
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    last_health timestamp with time zone,
    priority integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: share_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.share_link (
    link_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    resource_type character varying(20) NOT NULL,
    resource_id uuid,
    label character varying(200),
    expires_at timestamp with time zone NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    access_count integer DEFAULT 0 NOT NULL,
    last_accessed timestamp with time zone,
    project_id character(14) NOT NULL
);


--
-- Name: sovereignty_zone; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sovereignty_zone (
    code character(2) NOT NULL,
    parent_code character(2),
    name character varying(50) NOT NULL,
    display character varying(100) NOT NULL,
    legal_note character varying(255),
    compliance_level character varying(100),
    fallback_zone character(2),
    auto_detect jsonb DEFAULT '{}'::jsonb NOT NULL,
    requires_approval boolean DEFAULT false NOT NULL,
    requires_mfa boolean DEFAULT false NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sso_provider; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sso_provider (
    provider_id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(200) NOT NULL,
    provider_type character varying(30) NOT NULL,
    client_id text NOT NULL,
    client_secret_enc bytea NOT NULL,
    client_secret_nonce bytea NOT NULL,
    issuer_url text,
    tenant_id text,
    extra_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    display_order smallint DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: system_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_config (
    key character varying(100) NOT NULL,
    value text NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: system_health; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_health (
    id bigint NOT NULL,
    checked_at timestamp with time zone DEFAULT now() NOT NULL,
    check_name character varying(50) NOT NULL,
    status character varying(10) NOT NULL,
    value text,
    message text,
    details jsonb
);


--
-- Name: system_health_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.system_health_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: system_health_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.system_health_id_seq OWNED BY public.system_health.id;


--
-- Name: test_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_config (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    description text,
    endpoint_kind text NOT NULL,
    endpoint_ref jsonb NOT NULL,
    workload jsonb NOT NULL,
    methodology jsonb,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    baseline_run_id uuid,
    max_duration_secs integer DEFAULT 900 NOT NULL,
    CONSTRAINT test_config_endpoint_kind_check CHECK ((endpoint_kind = ANY (ARRAY['network'::text, 'proxy'::text, 'runtime'::text, 'pending'::text])))
);


--
-- Name: test_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    test_config_id uuid NOT NULL,
    project_id text NOT NULL,
    status text NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    success_count integer DEFAULT 0 NOT NULL,
    failure_count integer DEFAULT 0 NOT NULL,
    error_message text,
    artifact_id uuid,
    tester_id uuid,
    worker_id text,
    last_heartbeat timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    comparison_group_id uuid,
    provisioning_deployment_id uuid,
    CONSTRAINT test_run_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'provisioning'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])))
);


--
-- Name: test_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_schedule (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    test_config_id uuid NOT NULL,
    project_id text NOT NULL,
    cron_expr text NOT NULL,
    timezone text DEFAULT 'UTC'::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    last_fired_at timestamp with time zone,
    last_run_id uuid,
    next_fire_at timestamp with time zone,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: test_visibility_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_visibility_rule (
    rule_id uuid NOT NULL,
    user_id uuid,
    resource_type character varying(20) NOT NULL,
    resource_id uuid NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    project_id character(14) NOT NULL
);


--
-- Name: vm_lifecycle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vm_lifecycle (
    event_id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id character varying(20) NOT NULL,
    resource_type text NOT NULL,
    resource_id uuid NOT NULL,
    resource_name text,
    cloud text NOT NULL,
    region text,
    vm_size text,
    vm_name text,
    vm_resource_id text,
    cloud_connection_id uuid,
    cloud_account_name_at_event text,
    provider_account_id text,
    event_type text NOT NULL,
    event_time timestamp with time zone NOT NULL,
    triggered_by uuid,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT vm_lifecycle_event_type_valid CHECK ((event_type = ANY (ARRAY['created'::text, 'started'::text, 'stopped'::text, 'deleted'::text, 'auto_shutdown'::text, 'error'::text]))),
    CONSTRAINT vm_lifecycle_resource_type_valid CHECK ((resource_type = ANY (ARRAY['tester'::text, 'endpoint'::text, 'benchmark'::text])))
);


--
-- Name: workspace_invite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_invite (
    invite_id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    role character varying(20) DEFAULT 'viewer'::character varying NOT NULL,
    token_hash character varying(128) NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    invited_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    accepted_at timestamp with time zone,
    accepted_by uuid,
    project_id character(14) NOT NULL
);


--
-- Name: workspace_warning; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_warning (
    warning_id uuid DEFAULT gen_random_uuid() NOT NULL,
    warning_type character varying(30) NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    project_id character(14) NOT NULL
);


--
-- Name: perf_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perf_log ALTER COLUMN id SET DEFAULT nextval('public.perf_log_id_seq'::regclass);


--
-- Name: system_health id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_health ALTER COLUMN id SET DEFAULT nextval('public.system_health_id_seq'::regclass);


--
-- Name: _migrations _migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._migrations
    ADD CONSTRAINT _migrations_pkey PRIMARY KEY (version);


--
-- Name: agent agent_api_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT agent_api_key_key UNIQUE (api_key);


--
-- Name: agent_command agent_command_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_command
    ADD CONSTRAINT agent_command_pkey PRIMARY KEY (command_id);


--
-- Name: agent agent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT agent_pkey PRIMARY KEY (agent_id);


--
-- Name: alert_channel alert_channel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_channel
    ADD CONSTRAINT alert_channel_pkey PRIMARY KEY (channel_id);


--
-- Name: alert_event alert_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_event
    ADD CONSTRAINT alert_event_pkey PRIMARY KEY (event_id);


--
-- Name: alert_rule alert_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_rule
    ADD CONSTRAINT alert_rule_pkey PRIMARY KEY (rule_id);


--
-- Name: benchmark_artifact benchmark_artifact_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benchmark_artifact
    ADD CONSTRAINT benchmark_artifact_pkey PRIMARY KEY (id);


--
-- Name: benchmark_testbed benchmark_cell_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benchmark_testbed
    ADD CONSTRAINT benchmark_cell_pkey PRIMARY KEY (testbed_id);


--
-- Name: benchmark_vm_catalog benchmark_vm_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benchmark_vm_catalog
    ADD CONSTRAINT benchmark_vm_catalog_pkey PRIMARY KEY (vm_id);


--
-- Name: cloud_account cloud_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloud_account
    ADD CONSTRAINT cloud_account_pkey PRIMARY KEY (account_id);


--
-- Name: cloud_connection cloud_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloud_connection
    ADD CONSTRAINT cloud_connection_pkey PRIMARY KEY (connection_id);


--
-- Name: command_approval command_approval_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_approval
    ADD CONSTRAINT command_approval_pkey PRIMARY KEY (approval_id);


--
-- Name: comparison_group comparison_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comparison_group
    ADD CONSTRAINT comparison_group_pkey PRIMARY KEY (id);


--
-- Name: cost_rate cost_rate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cost_rate
    ADD CONSTRAINT cost_rate_pkey PRIMARY KEY (cost_rate_id);


--
-- Name: dash_user dash_user_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dash_user
    ADD CONSTRAINT dash_user_email_unique UNIQUE (email);


--
-- Name: dash_user dash_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dash_user
    ADD CONSTRAINT dash_user_pkey PRIMARY KEY (user_id);


--
-- Name: deployment deployment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_pkey PRIMARY KEY (deployment_id);


--
-- Name: migration_audit_log migration_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_audit_log
    ADD CONSTRAINT migration_audit_log_pkey PRIMARY KEY (log_id);


--
-- Name: migration_request migration_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_request
    ADD CONSTRAINT migration_request_pkey PRIMARY KEY (request_id);


--
-- Name: perf_log perf_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perf_log
    ADD CONSTRAINT perf_log_pkey PRIMARY KEY (id);


--
-- Name: project_member project_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_pkey PRIMARY KEY (project_id, user_id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (project_id);


--
-- Name: project_routing project_routing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_routing
    ADD CONSTRAINT project_routing_pkey PRIMARY KEY (project_id);


--
-- Name: project project_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_slug_key UNIQUE (slug);


--
-- Name: project_tester project_tester_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_tester
    ADD CONSTRAINT project_tester_pkey PRIMARY KEY (tester_id);


--
-- Name: project_tester project_tester_project_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_tester
    ADD CONSTRAINT project_tester_project_id_name_key UNIQUE (project_id, name);


--
-- Name: server_registry server_registry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_registry
    ADD CONSTRAINT server_registry_pkey PRIMARY KEY (zone_code, server_id);


--
-- Name: share_link share_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_link
    ADD CONSTRAINT share_link_pkey PRIMARY KEY (link_id);


--
-- Name: share_link share_link_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_link
    ADD CONSTRAINT share_link_token_hash_key UNIQUE (token_hash);


--
-- Name: sovereignty_zone sovereignty_zone_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sovereignty_zone
    ADD CONSTRAINT sovereignty_zone_name_key UNIQUE (name);


--
-- Name: sovereignty_zone sovereignty_zone_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sovereignty_zone
    ADD CONSTRAINT sovereignty_zone_pkey PRIMARY KEY (code);


--
-- Name: sso_provider sso_provider_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sso_provider
    ADD CONSTRAINT sso_provider_pkey PRIMARY KEY (provider_id);


--
-- Name: system_config system_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_config
    ADD CONSTRAINT system_config_pkey PRIMARY KEY (key);


--
-- Name: system_health system_health_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_health
    ADD CONSTRAINT system_health_pkey PRIMARY KEY (id);


--
-- Name: test_config test_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_config
    ADD CONSTRAINT test_config_pkey PRIMARY KEY (id);


--
-- Name: test_config test_config_project_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_config
    ADD CONSTRAINT test_config_project_id_name_key UNIQUE (project_id, name);


--
-- Name: test_run test_run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_pkey PRIMARY KEY (id);


--
-- Name: test_schedule test_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_schedule
    ADD CONSTRAINT test_schedule_pkey PRIMARY KEY (id);


--
-- Name: test_visibility_rule test_visibility_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_visibility_rule
    ADD CONSTRAINT test_visibility_rule_pkey PRIMARY KEY (rule_id);


--
-- Name: vm_lifecycle vm_lifecycle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vm_lifecycle
    ADD CONSTRAINT vm_lifecycle_pkey PRIMARY KEY (event_id);


--
-- Name: workspace_invite workspace_invite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_invite
    ADD CONSTRAINT workspace_invite_pkey PRIMARY KEY (invite_id);


--
-- Name: workspace_warning workspace_warning_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_warning
    ADD CONSTRAINT workspace_warning_pkey PRIMARY KEY (warning_id);


--
-- Name: agent_api_key_hash_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agent_api_key_hash_key ON public.agent USING btree (api_key_hash);


--
-- Name: idx_agent_command_agent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_command_agent ON public.agent_command USING btree (agent_id, created_at DESC);


--
-- Name: idx_agent_command_config; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_command_config ON public.agent_command USING btree (config_id) WHERE (config_id IS NOT NULL);


--
-- Name: idx_agent_tester; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_tester ON public.agent USING btree (tester_id) WHERE (tester_id IS NOT NULL);


--
-- Name: idx_cost_rate_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cost_rate_lookup ON public.cost_rate USING btree (cloud, vm_size, region, effective_from DESC);


--
-- Name: idx_project_tester_alloc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_tester_alloc ON public.project_tester USING btree (allocation) WHERE (allocation = ANY (ARRAY['idle'::text, 'locked'::text]));


--
-- Name: idx_project_tester_cloud_conn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_tester_cloud_conn ON public.project_tester USING btree (cloud_connection_id) WHERE (cloud_connection_id IS NOT NULL);


--
-- Name: idx_project_tester_last_used; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_tester_last_used ON public.project_tester USING btree (project_id, last_used_at DESC NULLS LAST);


--
-- Name: idx_project_tester_power; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_tester_power ON public.project_tester USING btree (power_state) WHERE (power_state = ANY (ARRAY['running'::text, 'stopped'::text]));


--
-- Name: idx_project_tester_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_tester_project ON public.project_tester USING btree (project_id);


--
-- Name: idx_project_tester_shutdown; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_tester_shutdown ON public.project_tester USING btree (next_shutdown_at) WHERE (auto_shutdown_enabled = true);


--
-- Name: idx_vm_lifecycle_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vm_lifecycle_account ON public.vm_lifecycle USING btree (provider_account_id, event_time DESC) WHERE (provider_account_id IS NOT NULL);


--
-- Name: idx_vm_lifecycle_project_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vm_lifecycle_project_time ON public.vm_lifecycle USING btree (project_id, event_time DESC);


--
-- Name: idx_vm_lifecycle_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vm_lifecycle_resource ON public.vm_lifecycle USING btree (resource_type, resource_id, event_time DESC);


--
-- Name: ix_agent_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_agent_project ON public.agent USING btree (project_id);


--
-- Name: ix_agent_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_agent_status ON public.agent USING btree (status);


--
-- Name: ix_alert_channel_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_channel_project ON public.alert_channel USING btree (project_id);


--
-- Name: ix_alert_event_rule; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_event_rule ON public.alert_event USING btree (rule_id, fired_at DESC);


--
-- Name: ix_alert_event_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_event_run ON public.alert_event USING btree (run_id);


--
-- Name: ix_alert_rule_config; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_rule_config ON public.alert_rule USING btree (test_config_id) WHERE (test_config_id IS NOT NULL);


--
-- Name: ix_alert_rule_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_rule_project ON public.alert_rule USING btree (project_id);


--
-- Name: ix_benchmark_artifact_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_benchmark_artifact_run ON public.benchmark_artifact USING btree (test_run_id);


--
-- Name: ix_benchmark_testbed_config; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_benchmark_testbed_config ON public.benchmark_testbed USING btree (config_id);


--
-- Name: ix_benchmark_vm_catalog_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_benchmark_vm_catalog_project ON public.benchmark_vm_catalog USING btree (project_id);


--
-- Name: ix_cloud_account_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cloud_account_owner ON public.cloud_account USING btree (owner_id) WHERE (owner_id IS NOT NULL);


--
-- Name: ix_cloud_account_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cloud_account_project ON public.cloud_account USING btree (project_id);


--
-- Name: ix_cloud_connection_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cloud_connection_provider ON public.cloud_connection USING btree (provider);


--
-- Name: ix_command_approval_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_command_approval_pending ON public.command_approval USING btree (project_id, status) WHERE ((status)::text = 'pending'::text);


--
-- Name: ix_comparison_group_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_comparison_group_project ON public.comparison_group USING btree (project_id);


--
-- Name: ix_deployment_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_deployment_project ON public.deployment USING btree (project_id, status, created_at DESC);


--
-- Name: ix_deployment_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_deployment_status ON public.deployment USING btree (status, created_at DESC);


--
-- Name: ix_migration_audit_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_migration_audit_request ON public.migration_audit_log USING btree (request_id, created_at);


--
-- Name: ix_perf_log_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_perf_log_kind ON public.perf_log USING btree (kind, logged_at DESC);


--
-- Name: ix_perf_log_logged_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_perf_log_logged_at ON public.perf_log USING btree (logged_at DESC);


--
-- Name: ix_perf_log_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_perf_log_path ON public.perf_log USING btree (path, logged_at DESC) WHERE ((kind)::text = 'api'::text);


--
-- Name: ix_perf_log_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_perf_log_user ON public.perf_log USING btree (user_id, logged_at DESC);


--
-- Name: ix_project_member_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_project_member_user ON public.project_member USING btree (user_id);


--
-- Name: ix_project_routing_current; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_project_routing_current ON public.project_routing USING btree (current_zone, home_zone);


--
-- Name: ix_project_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_project_slug ON public.project USING btree (slug);


--
-- Name: ix_project_zone_prefix; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_project_zone_prefix ON public.project USING btree (SUBSTRING(project_id FROM 1 FOR 2));


--
-- Name: ix_server_registry_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_server_registry_status ON public.server_registry USING btree (zone_code, status);


--
-- Name: ix_share_link_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_share_link_expires ON public.share_link USING btree (expires_at) WHERE (revoked = false);


--
-- Name: ix_share_link_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_share_link_project ON public.share_link USING btree (project_id, resource_type);


--
-- Name: ix_share_link_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_share_link_token ON public.share_link USING btree (token_hash) WHERE (revoked = false);


--
-- Name: ix_system_health_checked_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_system_health_checked_at ON public.system_health USING btree (checked_at DESC);


--
-- Name: ix_system_health_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_system_health_name ON public.system_health USING btree (check_name, checked_at DESC);


--
-- Name: ix_test_config_endpoint_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_config_endpoint_kind ON public.test_config USING btree (endpoint_kind);


--
-- Name: ix_test_config_is_benchmark; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_config_is_benchmark ON public.test_config USING btree (((methodology IS NOT NULL)));


--
-- Name: ix_test_config_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_config_project ON public.test_config USING btree (project_id);


--
-- Name: ix_test_run_comparison; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_run_comparison ON public.test_run USING btree (comparison_group_id) WHERE (comparison_group_id IS NOT NULL);


--
-- Name: ix_test_run_config; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_run_config ON public.test_run USING btree (test_config_id);


--
-- Name: ix_test_run_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_run_created ON public.test_run USING btree (created_at DESC);


--
-- Name: ix_test_run_project_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_run_project_status ON public.test_run USING btree (project_id, status);


--
-- Name: ix_test_run_provisioning; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_run_provisioning ON public.test_run USING btree (provisioning_deployment_id) WHERE (provisioning_deployment_id IS NOT NULL);


--
-- Name: ix_test_schedule_config; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_schedule_config ON public.test_schedule USING btree (test_config_id);


--
-- Name: ix_test_schedule_enabled_next; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_test_schedule_enabled_next ON public.test_schedule USING btree (enabled, next_fire_at);


--
-- Name: ix_user_sso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_sso ON public.dash_user USING btree (auth_provider, sso_subject_id) WHERE (sso_subject_id IS NOT NULL);


--
-- Name: ix_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_status ON public.dash_user USING btree (status);


--
-- Name: ix_visibility_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_visibility_project ON public.test_visibility_rule USING btree (project_id, user_id, resource_type);


--
-- Name: ix_workspace_invite_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workspace_invite_project ON public.workspace_invite USING btree (project_id, status);


--
-- Name: ix_workspace_invite_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workspace_invite_token ON public.workspace_invite USING btree (token_hash);


--
-- Name: ix_workspace_warning_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_workspace_warning_unique ON public.workspace_warning USING btree (project_id, warning_type);


--
-- Name: agent_command agent_command_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_command
    ADD CONSTRAINT agent_command_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent(agent_id) ON DELETE CASCADE;


--
-- Name: agent_command agent_command_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_command
    ADD CONSTRAINT agent_command_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: agent agent_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT agent_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: agent agent_tester_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT agent_tester_id_fkey FOREIGN KEY (tester_id) REFERENCES public.project_tester(tester_id) ON DELETE SET NULL;


--
-- Name: alert_channel alert_channel_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_channel
    ADD CONSTRAINT alert_channel_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: alert_event alert_event_rule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_event
    ADD CONSTRAINT alert_event_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.alert_rule(rule_id) ON DELETE CASCADE;


--
-- Name: alert_event alert_event_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_event
    ADD CONSTRAINT alert_event_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.test_run(id) ON DELETE CASCADE;


--
-- Name: alert_rule alert_rule_channel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_rule
    ADD CONSTRAINT alert_rule_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.alert_channel(channel_id);


--
-- Name: alert_rule alert_rule_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_rule
    ADD CONSTRAINT alert_rule_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: alert_rule alert_rule_test_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_rule
    ADD CONSTRAINT alert_rule_test_config_id_fkey FOREIGN KEY (test_config_id) REFERENCES public.test_config(id) ON DELETE CASCADE;


--
-- Name: benchmark_artifact benchmark_artifact_test_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benchmark_artifact
    ADD CONSTRAINT benchmark_artifact_test_run_id_fkey FOREIGN KEY (test_run_id) REFERENCES public.test_run(id) ON DELETE CASCADE;


--
-- Name: benchmark_vm_catalog benchmark_vm_catalog_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benchmark_vm_catalog
    ADD CONSTRAINT benchmark_vm_catalog_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: benchmark_vm_catalog benchmark_vm_catalog_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benchmark_vm_catalog
    ADD CONSTRAINT benchmark_vm_catalog_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: cloud_account cloud_account_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloud_account
    ADD CONSTRAINT cloud_account_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.dash_user(user_id) ON DELETE CASCADE;


--
-- Name: cloud_account cloud_account_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloud_account
    ADD CONSTRAINT cloud_account_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: cloud_connection cloud_connection_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloud_connection
    ADD CONSTRAINT cloud_connection_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: cloud_connection cloud_connection_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloud_connection
    ADD CONSTRAINT cloud_connection_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: command_approval command_approval_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_approval
    ADD CONSTRAINT command_approval_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent(agent_id) ON DELETE CASCADE;


--
-- Name: command_approval command_approval_decided_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_approval
    ADD CONSTRAINT command_approval_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.dash_user(user_id);


--
-- Name: command_approval command_approval_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_approval
    ADD CONSTRAINT command_approval_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: command_approval command_approval_requested_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_approval
    ADD CONSTRAINT command_approval_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.dash_user(user_id);


--
-- Name: comparison_group comparison_group_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comparison_group
    ADD CONSTRAINT comparison_group_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: deployment deployment_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent(agent_id);


--
-- Name: deployment deployment_cloud_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_cloud_account_id_fkey FOREIGN KEY (cloud_account_id) REFERENCES public.cloud_account(account_id);


--
-- Name: deployment deployment_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: deployment deployment_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: migration_audit_log migration_audit_log_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_audit_log
    ADD CONSTRAINT migration_audit_log_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.migration_request(request_id);


--
-- Name: migration_request migration_request_approved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_request
    ADD CONSTRAINT migration_request_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.dash_user(user_id);


--
-- Name: migration_request migration_request_from_zone_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_request
    ADD CONSTRAINT migration_request_from_zone_fkey FOREIGN KEY (from_zone) REFERENCES public.sovereignty_zone(code);


--
-- Name: migration_request migration_request_requested_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_request
    ADD CONSTRAINT migration_request_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.dash_user(user_id);


--
-- Name: migration_request migration_request_to_zone_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_request
    ADD CONSTRAINT migration_request_to_zone_fkey FOREIGN KEY (to_zone) REFERENCES public.sovereignty_zone(code);


--
-- Name: perf_log perf_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perf_log
    ADD CONSTRAINT perf_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.dash_user(user_id);


--
-- Name: project project_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: project_member project_member_invited_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.dash_user(user_id);


--
-- Name: project_member project_member_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: project_member project_member_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.dash_user(user_id) ON DELETE CASCADE;


--
-- Name: project_routing project_routing_current_zone_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_routing
    ADD CONSTRAINT project_routing_current_zone_fkey FOREIGN KEY (current_zone) REFERENCES public.sovereignty_zone(code);


--
-- Name: project_routing project_routing_home_zone_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_routing
    ADD CONSTRAINT project_routing_home_zone_fkey FOREIGN KEY (home_zone) REFERENCES public.sovereignty_zone(code);


--
-- Name: project_tester project_tester_cloud_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_tester
    ADD CONSTRAINT project_tester_cloud_account_id_fkey FOREIGN KEY (cloud_account_id) REFERENCES public.cloud_account(account_id) ON DELETE SET NULL;


--
-- Name: project_tester project_tester_cloud_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_tester
    ADD CONSTRAINT project_tester_cloud_connection_id_fkey FOREIGN KEY (cloud_connection_id) REFERENCES public.cloud_connection(connection_id) ON DELETE RESTRICT;


--
-- Name: project_tester project_tester_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_tester
    ADD CONSTRAINT project_tester_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: project_tester project_tester_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_tester
    ADD CONSTRAINT project_tester_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: server_registry server_registry_zone_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_registry
    ADD CONSTRAINT server_registry_zone_code_fkey FOREIGN KEY (zone_code) REFERENCES public.sovereignty_zone(code);


--
-- Name: share_link share_link_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_link
    ADD CONSTRAINT share_link_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: share_link share_link_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_link
    ADD CONSTRAINT share_link_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: sovereignty_zone sovereignty_zone_fallback_zone_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sovereignty_zone
    ADD CONSTRAINT sovereignty_zone_fallback_zone_fkey FOREIGN KEY (fallback_zone) REFERENCES public.sovereignty_zone(code);


--
-- Name: sovereignty_zone sovereignty_zone_parent_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sovereignty_zone
    ADD CONSTRAINT sovereignty_zone_parent_code_fkey FOREIGN KEY (parent_code) REFERENCES public.sovereignty_zone(code);


--
-- Name: sso_provider sso_provider_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sso_provider
    ADD CONSTRAINT sso_provider_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: system_config system_config_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_config
    ADD CONSTRAINT system_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.dash_user(user_id);


--
-- Name: test_config test_config_baseline_run_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_config
    ADD CONSTRAINT test_config_baseline_run_fk FOREIGN KEY (baseline_run_id) REFERENCES public.test_run(id) ON DELETE SET NULL;


--
-- Name: test_config test_config_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_config
    ADD CONSTRAINT test_config_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id) ON DELETE SET NULL;


--
-- Name: test_config test_config_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_config
    ADD CONSTRAINT test_config_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: test_run test_run_artifact_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_artifact_fk FOREIGN KEY (artifact_id) REFERENCES public.benchmark_artifact(id) ON DELETE SET NULL;


--
-- Name: test_run test_run_comparison_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_comparison_group_id_fkey FOREIGN KEY (comparison_group_id) REFERENCES public.comparison_group(id) ON DELETE SET NULL;


--
-- Name: test_run test_run_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: test_run test_run_provisioning_deployment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_provisioning_deployment_id_fkey FOREIGN KEY (provisioning_deployment_id) REFERENCES public.deployment(deployment_id) ON DELETE SET NULL;


--
-- Name: test_run test_run_test_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_test_config_id_fkey FOREIGN KEY (test_config_id) REFERENCES public.test_config(id) ON DELETE CASCADE;


--
-- Name: test_run test_run_tester_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run
    ADD CONSTRAINT test_run_tester_id_fkey FOREIGN KEY (tester_id) REFERENCES public.project_tester(tester_id) ON DELETE SET NULL;


--
-- Name: test_schedule test_schedule_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_schedule
    ADD CONSTRAINT test_schedule_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id) ON DELETE SET NULL;


--
-- Name: test_schedule test_schedule_last_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_schedule
    ADD CONSTRAINT test_schedule_last_run_id_fkey FOREIGN KEY (last_run_id) REFERENCES public.test_run(id) ON DELETE SET NULL;


--
-- Name: test_schedule test_schedule_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_schedule
    ADD CONSTRAINT test_schedule_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: test_schedule test_schedule_test_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_schedule
    ADD CONSTRAINT test_schedule_test_config_id_fkey FOREIGN KEY (test_config_id) REFERENCES public.test_config(id) ON DELETE CASCADE;


--
-- Name: test_visibility_rule test_visibility_rule_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_visibility_rule
    ADD CONSTRAINT test_visibility_rule_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.dash_user(user_id);


--
-- Name: test_visibility_rule test_visibility_rule_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_visibility_rule
    ADD CONSTRAINT test_visibility_rule_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: test_visibility_rule test_visibility_rule_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_visibility_rule
    ADD CONSTRAINT test_visibility_rule_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.dash_user(user_id) ON DELETE CASCADE;


--
-- Name: vm_lifecycle vm_lifecycle_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vm_lifecycle
    ADD CONSTRAINT vm_lifecycle_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: vm_lifecycle vm_lifecycle_triggered_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vm_lifecycle
    ADD CONSTRAINT vm_lifecycle_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES public.dash_user(user_id) ON DELETE SET NULL;


--
-- Name: workspace_invite workspace_invite_accepted_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_invite
    ADD CONSTRAINT workspace_invite_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES public.dash_user(user_id);


--
-- Name: workspace_invite workspace_invite_invited_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_invite
    ADD CONSTRAINT workspace_invite_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.dash_user(user_id);


--
-- Name: workspace_invite workspace_invite_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_invite
    ADD CONSTRAINT workspace_invite_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- Name: workspace_warning workspace_warning_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_warning
    ADD CONSTRAINT workspace_warning_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


