ALTER TABLE schedule ADD COLUMN IF NOT EXISTS auto_start_vm BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS auto_stop_vm BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS deployment_id UUID REFERENCES deployment(deployment_id);
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS name VARCHAR(200);
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS config JSONB;
ALTER TABLE schedule ALTER COLUMN definition_id DROP NOT NULL;
