using System.Globalization;
using Networker.ControlPlane.Endpoints;

namespace Networker.ControlPlane.Reports.Documents;

/// <summary>
/// Renders the Application-Network report (<see cref="AppNetworkReport"/>) as a
/// document: the overall server-vs-network split with a verdict, a per-endpoint
/// breakdown, and the formulas. Pure — maps the already-computed wire report,
/// adds no new statistics.
/// </summary>
public static class AppNetworkReportDocument
{
    public static ReportDocument Build(AppNetworkReport report, string projectId)
    {
        var sections = new List<ReportSection>();

        // ── Overall ──
        var overall = new List<ReportBlock>
        {
            new MetricsBlock(
                new Metric("Server p50", Ms(report.OverallMedianServerMs)),
                new Metric("Network p50", Ms(report.OverallMedianNetworkMs)),
                new Metric("Wall p50", Ms(report.OverallMedianWallMs)),
                new Metric("Server share", Ratio(report.OverallServerRatio))),
            new CalloutBlock(
                $"{VerdictLabel(report.OverallVerdict)} — {report.OverallMainIssue}",
                VerdictTone(report.OverallVerdict)),
        };
        if (report.OverallMedianServerMs is { } srv && report.OverallMedianNetworkMs is { } net)
        {
            overall.Add(new ChartBlock("Where the median request time goes", new[]
            {
                new ChartPoint("Server", srv, Ms(srv), ReportTone.Warn),
                new ChartPoint("Network", net, Ms(net), ReportTone.Info),
            }));
        }
        if (report.SplitAnomalyCount > 0)
        {
            overall.Add(new CalloutBlock(
                $"{report.SplitAnomalyCount} attempt(s) reported server time greater than wall time "
                + "(clock skew or SDK span mismatch); network time was floored at 0 for those.",
                ReportTone.Warn));
        }
        sections.Add(new ReportSection("Overall", overall));

        // ── By endpoint ──
        if (report.Groups.Count > 0)
        {
            var rows = report.Groups
                .Select(g => (IReadOnlyList<string>)new[]
                {
                    g.ConfigName,
                    g.RunCount.ToString(CultureInfo.InvariantCulture),
                    g.AttemptCount.ToString(CultureInfo.InvariantCulture),
                    Ms(g.MedianServerMs),
                    Ms(g.P95ServerMs),
                    Ms(g.MedianNetworkMs),
                    Ms(g.P95NetworkMs),
                    Ratio(g.ServerRatio),
                    VerdictLabel(g.Verdict),
                })
                .ToList();

            sections.Add(new ReportSection("By endpoint", new TableBlock(
                Headers: new[] { "Endpoint", "Runs", "Attempts", "Srv p50", "Srv p95", "Net p50", "Net p95", "Server %", "Verdict" },
                Rows: rows,
                Aligns: new[]
                {
                    ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
                    ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Left,
                })));
        }
        else
        {
            sections.Add(new ReportSection("By endpoint",
                new ProseBlock("No completed SDK-probe attempts for this project yet.")));
        }

        // ── How it's measured ──
        sections.Add(new ReportSection("How it's measured",
            new ProseBlock(report.Formulas.ServerMs),
            new ProseBlock(report.Formulas.NetworkMs),
            new ProseBlock(report.Formulas.Split)));

        return new ReportDocument(
            Title: "Application Network Performance",
            Subtitle: "Is the slowness the application or the network?",
            GeneratedAt: report.GeneratedAt,
            Meta: new[]
            {
                new ReportMeta("Project", projectId),
                new ReportMeta("Mode", report.Mode),
                new ReportMeta("Attempts", report.AttemptCount.ToString(CultureInfo.InvariantCulture)),
            },
            Sections: sections,
            FooterNote: $"Generated by {ReportBranding.ProductName}. Server time is the SDK's "
                + "Server-Timing header; network time is wall minus server.");
    }

    private static string VerdictLabel(string verdict) => verdict switch
    {
        AppNetworkLogic.VerdictServerBound => "Application-bound",
        AppNetworkLogic.VerdictNetworkBound => "Network-bound",
        AppNetworkLogic.VerdictBalanced => "Balanced",
        _ => "No data",
    };

    private static ReportTone VerdictTone(string verdict) => verdict switch
    {
        AppNetworkLogic.VerdictServerBound => ReportTone.Warn,
        AppNetworkLogic.VerdictNetworkBound => ReportTone.Info,
        AppNetworkLogic.VerdictBalanced => ReportTone.Neutral,
        _ => ReportTone.Neutral,
    };

    private static string Ms(double? v) =>
        v is { } d ? d.ToString(d >= 100 ? "0" : "0.0", CultureInfo.InvariantCulture) + " ms" : "—";

    private static string Ratio(double? fraction) =>
        fraction is { } f ? (f * 100).ToString("0.#", CultureInfo.InvariantCulture) + "%" : "—";
}
