using System.Globalization;
using Networker.ControlPlane.Endpoints;
using Networker.ControlPlane.Reports;

namespace Networker.ControlPlane.Reports.Documents;

/// <summary>
/// The data the project-level <b>Integrated Test Report</b> renders — an
/// executive summary plus the details of every test in one exportable
/// document. Assembled by <c>IntegratedReportEndpoints</c>; the analysis
/// reports are the SAME records the standalone routes serve (built by the
/// shared <c>BuildReportAsync</c> helpers) so the integrated view can never
/// disagree with them.
/// </summary>
public sealed record IntegratedReportInput(
    string ProjectId,
    string ProjectName,
    IReadOnlyList<RunStatusCount> RunStatuses,
    DateTime? FirstRunAt,
    DateTime? LastRunAt,
    IReadOnlyList<ConfigResult> Configs,
    IReadOnlyList<ProtocolResult> Protocols,
    AppNetworkReport? AppNetwork,
    PerfPerCostReport? PerfPerCost,
    IReadOnlyList<RecentRunRow> RecentRuns);

/// <summary>Run count for one lifecycle status (completed / failed / …).</summary>
public sealed record RunStatusCount(string Status, int Count);

/// <summary>Aggregated result of one test config over its completed runs.</summary>
public sealed record ConfigResult(
    Guid ConfigId,
    string Name,
    string Workload,
    int RunCount,
    DateTime? LastRunAt,
    int AttemptCount,
    int OkCount,
    double? P50Ms,
    double? P95Ms);

/// <summary>Project-wide latency distribution of one probe protocol.</summary>
public sealed record ProtocolResult(
    string Protocol,
    int AttemptCount,
    int OkCount,
    double? MinMs,
    double? P25Ms,
    double? P50Ms,
    double? P75Ms,
    double? P95Ms,
    double? MaxMs);

/// <summary>One row of the recent-runs detail table.</summary>
public sealed record RecentRunRow(
    Guid RunId,
    string ConfigName,
    string Status,
    DateTime? StartedAt,
    DateTime? FinishedAt,
    int SuccessCount,
    int FailureCount);

/// <summary>
/// Builds the Integrated Test Report: an executive summary (KPIs, verdict,
/// runs-by-status), results per test, the per-protocol latency distribution,
/// condensed application-vs-network and perf-per-cost analyses, and a
/// recent-runs detail table. Pure — no I/O.
/// </summary>
public static class IntegratedReportDocument
{
    /// <summary>Configs charted in the p95 comparison (all still appear in the table).</summary>
    public const int MaxChartedConfigs = 8;

    public const int MaxRecentRuns = 15;

    public static ReportDocument Build(IntegratedReportInput input)
    {
        var sections = new List<ReportSection>
        {
            ExecutiveSummary(input),
        };

        if (input.Configs.Count > 0)
        {
            sections.Add(ResultsByTest(input.Configs));
        }
        if (input.Protocols.Count > 0)
        {
            sections.Add(LatencyByProtocol(input.Protocols));
        }
        if (input.AppNetwork is { AttemptCount: > 0 } appNet)
        {
            sections.Add(AppNetworkSection(appNet));
        }
        if (input.PerfPerCost is { Groups.Count: > 0 } perf)
        {
            sections.Add(PerfPerCostSection(perf));
        }
        if (input.RecentRuns.Count > 0)
        {
            sections.Add(RecentRunsSection(input.RecentRuns));
        }

        var totalRuns = input.RunStatuses.Sum(s => s.Count);
        var meta = new List<ReportMeta>
        {
            new("Project", input.ProjectName),
            new("Tests", input.Configs.Count.ToString(CultureInfo.InvariantCulture)),
            new("Runs", totalRuns.ToString(CultureInfo.InvariantCulture)),
        };
        if (input.FirstRunAt is { } first && input.LastRunAt is { } last)
        {
            meta.Add(new ReportMeta("Window",
                $"{first:yyyy-MM-dd} → {last:yyyy-MM-dd}"));
        }

        return new ReportDocument(
            Title: "Integrated Test Report",
            Subtitle: $"All test results for {input.ProjectName} — summary and details",
            GeneratedAt: DateTime.UtcNow,
            Meta: meta,
            Sections: sections,
            FooterNote: $"Generated by {ReportBranding.ProductName}. Aggregates cover completed runs; "
                + "per-attempt detail for any single run is available from that run's own report export.");
    }

    // ── sections ─────────────────────────────────────────────────────────────

    private static ReportSection ExecutiveSummary(IntegratedReportInput input)
    {
        var totalRuns = input.RunStatuses.Sum(s => s.Count);
        var completed = input.RunStatuses.Where(s => s.Status == "completed").Sum(s => s.Count);
        var attempts = input.Configs.Sum(c => (long)c.AttemptCount);
        var ok = input.Configs.Sum(c => (long)c.OkCount);
        var successRate = attempts > 0 ? 100.0 * ok / attempts : (double?)null;

        var blocks = new List<ReportBlock>
        {
            new MetricsBlock(
                new Metric("Tests", input.Configs.Count.ToString(CultureInfo.InvariantCulture)),
                new Metric("Runs", totalRuns.ToString(CultureInfo.InvariantCulture)),
                new Metric("Completed", completed.ToString(CultureInfo.InvariantCulture),
                    completed == totalRuns && totalRuns > 0 ? ReportTone.Good : ReportTone.Neutral),
                new Metric("Attempts", attempts.ToString(CultureInfo.InvariantCulture)),
                new Metric("Success rate",
                    successRate is { } r ? r.ToString("0.#", CultureInfo.InvariantCulture) + "%" : "—",
                    RateTone(successRate))),
            Verdict(input, totalRuns, completed, successRate),
        };

        // App-vs-network headline, when that analysis has data — the single most
        // decision-relevant line the project report can carry.
        if (input.AppNetwork is { AttemptCount: > 0 } appNet)
        {
            blocks.Add(new CalloutBlock(
                $"Application vs network: {AppNetworkVerdictLabel(appNet.OverallVerdict)} — {appNet.OverallMainIssue}",
                AppNetworkVerdictTone(appNet.OverallVerdict)));
        }

        if (totalRuns > 0)
        {
            blocks.Add(new ChartBlock("Runs by status", input.RunStatuses
                .OrderByDescending(s => s.Count)
                .Select(s => new ChartPoint(
                    s.Status, s.Count, s.Count.ToString(CultureInfo.InvariantCulture), StatusTone(s.Status)))
                .ToList()));
        }

        return new ReportSection("Executive summary", blocks);
    }

    private static ReportSection ResultsByTest(IReadOnlyList<ConfigResult> configs)
    {
        var ordered = configs
            .OrderByDescending(c => c.LastRunAt ?? DateTime.MinValue)
            .ToList();

        var rows = ordered
            .Select(c => (IReadOnlyList<string>)new[]
            {
                c.Name,
                c.Workload,
                c.RunCount.ToString(CultureInfo.InvariantCulture),
                c.AttemptCount.ToString(CultureInfo.InvariantCulture),
                Rate(c.AttemptCount, c.OkCount),
                Ms(c.P50Ms),
                Ms(c.P95Ms),
                c.LastRunAt is { } t ? t.ToString("MM-dd HH:mm", CultureInfo.InvariantCulture) : "—",
            })
            .ToList();

        var blocks = new List<ReportBlock>();

        // p95 comparison across the most-recently-active tests.
        var charted = ordered
            .Where(c => c.P95Ms is not null)
            .Take(MaxChartedConfigs)
            .Select(c => new ChartPoint(Truncate(c.Name, 18), c.P95Ms!.Value, Ms(c.P95Ms)))
            .ToList();
        if (charted.Count > 1)
        {
            blocks.Add(new ChartBlock("p95 latency by test", charted));
        }

        blocks.Add(new TableBlock(
            Headers: new[] { "Test", "Workload", "Runs", "Attempts", "OK", "p50", "p95", "Last run (UTC)" },
            Rows: rows,
            Aligns: new[]
            {
                ColumnAlign.Left, ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right,
                ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Left,
            }));

        return new ReportSection("Results by test", blocks);
    }

    private static ReportSection LatencyByProtocol(IReadOnlyList<ProtocolResult> protocols)
    {
        var ordered = protocols.OrderBy(p => p.Protocol, StringComparer.Ordinal).ToList();

        var candles = ordered
            .Where(p => p.P50Ms is not null)
            .Select(p => new CandlePoint(
                p.Protocol.ToUpperInvariant(), p.MinMs, p.P25Ms, p.P50Ms, p.P75Ms, p.P95Ms, p.MaxMs))
            .ToList();

        var rows = ordered
            .Select(p => (IReadOnlyList<string>)new[]
            {
                p.Protocol.ToUpperInvariant(),
                p.AttemptCount.ToString(CultureInfo.InvariantCulture),
                Rate(p.AttemptCount, p.OkCount),
                Ms(p.P50Ms),
                Ms(p.P95Ms),
                Ms(p.MaxMs),
            })
            .ToList();

        var blocks = new List<ReportBlock>();
        if (candles.Count > 0)
        {
            blocks.Add(new CandleBlock("Latency distribution by protocol (completed runs)", candles, "ms"));
        }
        blocks.Add(new TableBlock(
            Headers: new[] { "Protocol", "Attempts", "OK", "p50", "p95", "max" },
            Rows: rows,
            Aligns: new[]
            {
                ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right,
                ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
            }));

        return new ReportSection("Latency by protocol", blocks);
    }

    /// <summary>Condensed application-vs-network analysis (the standalone
    /// app-network export carries the formulas and per-endpoint percentiles).</summary>
    private static ReportSection AppNetworkSection(AppNetworkReport report)
    {
        var blocks = new List<ReportBlock>
        {
            new MetricsBlock(
                new Metric("Server p50", Ms(report.OverallMedianServerMs)),
                new Metric("Network p50", Ms(report.OverallMedianNetworkMs)),
                new Metric("Wall p50", Ms(report.OverallMedianWallMs)),
                new Metric("Server share", Ratio(report.OverallServerRatio))),
        };
        if (report.OverallMedianServerMs is { } srv && report.OverallMedianNetworkMs is { } net)
        {
            blocks.Add(new ChartBlock("Where the median request time goes", new[]
            {
                new ChartPoint("Server", srv, Ms(srv), ReportTone.Warn),
                new ChartPoint("Network", net, Ms(net), ReportTone.Info),
            }));
        }
        if (report.Groups.Count > 0)
        {
            blocks.Add(new TableBlock(
                Headers: new[] { "Endpoint", "Attempts", "Srv p50", "Net p50", "Server %", "Verdict" },
                Rows: report.Groups
                    .Select(g => (IReadOnlyList<string>)new[]
                    {
                        g.ConfigName,
                        g.AttemptCount.ToString(CultureInfo.InvariantCulture),
                        Ms(g.MedianServerMs),
                        Ms(g.MedianNetworkMs),
                        Ratio(g.ServerRatio),
                        AppNetworkVerdictLabel(g.Verdict),
                    })
                    .ToList(),
                Aligns: new[]
                {
                    ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right,
                    ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Left,
                }));
        }
        return new ReportSection("Application vs network", blocks);
    }

    /// <summary>Condensed perf-per-cost analysis, one row per (group, family)
    /// (the standalone export carries provenance, formulas and missing SKUs).</summary>
    private static ReportSection PerfPerCostSection(PerfPerCostReport report)
    {
        var rows = new List<IReadOnlyList<string>>();
        foreach (var g in report.Groups)
        {
            foreach (var f in g.Families)
            {
                rows.Add(new[]
                {
                    $"{g.Provider} · {g.VmSize} · {g.Region}",
                    g.HourlyUsd is { } h ? "$" + h.ToString("0.####", CultureInfo.InvariantCulture) : "—",
                    f.Family,
                    Num(f.Median) + (f.MetricLabel == "throughput_mbps" ? " Mbps" : " ms"),
                    Num(f.ValueScore),
                });
            }
        }

        return new ReportSection("Performance per cost", new ReportBlock[]
        {
            new ProseBlock("Higher value score = better performance per dollar. Full provenance and "
                + "formulas are in the standalone perf-per-cost export."),
            new TableBlock(
                Headers: new[] { "Tester group", "$/hr", "Family", "Median", "Value score" },
                Rows: rows,
                Aligns: new[]
                {
                    ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Left,
                    ColumnAlign.Right, ColumnAlign.Right,
                }),
        });
    }

    private static ReportSection RecentRunsSection(IReadOnlyList<RecentRunRow> runs)
    {
        var rows = runs
            .Select(r => (IReadOnlyList<string>)new[]
            {
                r.RunId.ToString("N")[..8],
                r.ConfigName,
                r.Status,
                r.StartedAt is { } s ? s.ToString("MM-dd HH:mm", CultureInfo.InvariantCulture) : "—",
                Duration(r.StartedAt, r.FinishedAt) ?? "—",
                r.SuccessCount.ToString(CultureInfo.InvariantCulture),
                r.FailureCount.ToString(CultureInfo.InvariantCulture),
            })
            .ToList();

        return new ReportSection("Recent runs", new TableBlock(
            Headers: new[] { "Run", "Test", "Status", "Started (UTC)", "Duration", "OK", "Err" },
            Rows: rows,
            Aligns: new[]
            {
                ColumnAlign.Left, ColumnAlign.Left, ColumnAlign.Left, ColumnAlign.Left,
                ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
            }));
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private static CalloutBlock Verdict(
        IntegratedReportInput input, int totalRuns, int completed, double? successRate)
    {
        if (totalRuns == 0)
        {
            return new CalloutBlock("No test runs yet — launch a test to populate this report.",
                ReportTone.Neutral);
        }
        var failedRuns = input.RunStatuses
            .Where(s => s.Status is "failed" or "error")
            .Sum(s => s.Count);
        if (failedRuns > 0)
        {
            return new CalloutBlock(
                $"{failedRuns} of {totalRuns} runs failed; attempt success rate "
                + (successRate is { } r ? r.ToString("0.#", CultureInfo.InvariantCulture) + "%." : "n/a."),
                ReportTone.Bad);
        }
        return successRate switch
        {
            null => new CalloutBlock($"All {totalRuns} runs finished; no probe attempts recorded.",
                ReportTone.Neutral),
            >= 99.5 => new CalloutBlock(
                $"Healthy: {completed} completed runs, {successRate:0.#}% attempt success.",
                ReportTone.Good),
            >= 95 => new CalloutBlock(
                $"Mostly healthy: {successRate:0.#}% attempt success across {completed} completed runs.",
                ReportTone.Warn),
            _ => new CalloutBlock(
                $"Degraded: only {successRate:0.#}% of attempts succeeded across {completed} completed runs.",
                ReportTone.Bad),
        };
    }

    private static ReportTone StatusTone(string status) => status switch
    {
        "completed" => ReportTone.Good,
        "failed" or "error" => ReportTone.Bad,
        "cancelled" or "canceled" => ReportTone.Neutral,
        _ => ReportTone.Info, // queued / running / dispatched
    };

    private static ReportTone RateTone(double? rate) => rate switch
    {
        null => ReportTone.Neutral,
        >= 99.5 => ReportTone.Good,
        >= 95 => ReportTone.Warn,
        _ => ReportTone.Bad,
    };

    private static string AppNetworkVerdictLabel(string verdict) => verdict switch
    {
        AppNetworkLogic.VerdictServerBound => "Application-bound",
        AppNetworkLogic.VerdictNetworkBound => "Network-bound",
        AppNetworkLogic.VerdictBalanced => "Balanced",
        _ => "No data",
    };

    private static ReportTone AppNetworkVerdictTone(string verdict) => verdict switch
    {
        AppNetworkLogic.VerdictServerBound => ReportTone.Warn,
        AppNetworkLogic.VerdictNetworkBound => ReportTone.Info,
        _ => ReportTone.Neutral,
    };

    private static string Rate(int total, int ok) =>
        total > 0
            ? (100.0 * ok / total).ToString("0.#", CultureInfo.InvariantCulture) + "%"
            : "—";

    private static string Ms(double? v) =>
        v is { } d ? d.ToString(d >= 100 ? "0" : "0.0", CultureInfo.InvariantCulture) + " ms" : "—";

    private static string Ratio(double? fraction) =>
        fraction is { } f ? (f * 100).ToString("0.#", CultureInfo.InvariantCulture) + "%" : "—";

    private static string Num(double? v) =>
        v is { } d ? d.ToString("0.##", CultureInfo.InvariantCulture) : "—";

    private static string? Duration(DateTime? start, DateTime? end)
    {
        if (start is not { } s || end is not { } e || e < s)
        {
            return null;
        }
        var span = e - s;
        return span.TotalSeconds < 60
            ? span.TotalSeconds.ToString("0.0", CultureInfo.InvariantCulture) + " s"
            : $"{(int)span.TotalMinutes}m {span.Seconds}s";
    }

    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";
}
