using System.Globalization;
using Networker.ControlPlane.Endpoints;

namespace Networker.ControlPlane.Reports.Documents;

/// <summary>
/// Renders the Perf-per-Cost report (<see cref="PerfPerCostReport"/>) as a
/// document: one table per tester group (provider / VM size / region) with each
/// mode family's median metric and value score, plus the price-table provenance
/// and any SKUs missing from the cost table. Pure — maps the wire report.
/// </summary>
public static class PerfPerCostReportDocument
{
    public static ReportDocument Build(PerfPerCostReport report, string projectId)
    {
        var sections = new List<ReportSection>();

        sections.Add(new ReportSection("Overview",
            new MetricsBlock(
                new Metric("Providers", report.ProvidersWithData.ToString(CultureInfo.InvariantCulture)),
                new Metric("Tester groups", report.Groups.Count.ToString(CultureInfo.InvariantCulture)),
                new Metric("Completed runs", report.CompletedRuns.ToString(CultureInfo.InvariantCulture),
                    report.CompletedRuns > 0 ? ReportTone.Neutral : ReportTone.Warn)),
            report.Groups.Count == 0
                ? new CalloutBlock("No completed runs with priced tester groups yet.", ReportTone.Neutral)
                : new CalloutBlock(
                    "Higher value score = better performance per dollar. Latency families use a "
                    + "cost index (higher is better); throughput families use Mbps per $/hour.",
                    ReportTone.Info)));

        foreach (var g in report.Groups)
        {
            var blocks = new List<ReportBlock>();

            var price = g.HourlyUsd is { } h
                ? "$" + h.ToString("0.####", CultureInfo.InvariantCulture) + "/hr"
                : "no price";
            blocks.Add(new ProseBlock($"Region {g.Region} · {price}"
                + (g.CostNote is { Length: > 0 } note ? $" · {note}" : "")));

            var rows = g.Families
                .Select(f => (IReadOnlyList<string>)new[]
                {
                    f.Family,
                    f.RunCount.ToString(CultureInfo.InvariantCulture),
                    f.SampleCount.ToString(CultureInfo.InvariantCulture),
                    MetricLabel(f.MetricLabel),
                    Num(f.Median),
                    f.P95Ms is { } p ? p.ToString("0.#", CultureInfo.InvariantCulture) : "—",
                    Num(f.ValueScore),
                })
                .ToList();

            blocks.Add(new TableBlock(
                Headers: new[] { "Family", "Runs", "Samples", "Metric", "Median", "p95", "Value score" },
                Rows: rows,
                Aligns: new[]
                {
                    ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Left,
                    ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
                }));

            sections.Add(new ReportSection($"{g.Provider} · {g.VmSize}", blocks));
        }

        if (report.MissingCostSkus.Count > 0)
        {
            var rows = report.MissingCostSkus
                .Select(m => (IReadOnlyList<string>)new[] { m.Provider, m.VmSize, m.Region })
                .ToList();
            sections.Add(new ReportSection("SKUs missing from the price table",
                new ProseBlock("These tester groups ran but have no row in the curated price table, "
                    + "so no value score could be computed:"),
                new TableBlock(new[] { "Provider", "VM size", "Region" }, rows)));
        }

        sections.Add(new ReportSection("Cost table",
            new ProseBlock(report.CostTable.Disclaimer),
            new ProseBlock($"Source: {report.CostTable.Source} · as of {report.CostTable.AsOf}"),
            new ProseBlock(report.Formulas.LatencyCostIndex),
            new ProseBlock(report.Formulas.MbpsPerDollarHour)));

        return new ReportDocument(
            Title: "Perf-per-Cost Report",
            Subtitle: "Which provider gives the best performance per dollar",
            GeneratedAt: report.GeneratedAt,
            Meta: new[]
            {
                new ReportMeta("Project", projectId),
                new ReportMeta("Providers", report.ProvidersWithData.ToString(CultureInfo.InvariantCulture)),
                new ReportMeta("Completed runs", report.CompletedRuns.ToString(CultureInfo.InvariantCulture)),
            },
            Sections: sections,
            FooterNote: $"Generated by {ReportBranding.ProductName}. Prices are from a static curated "
                + "table; no pricing API is called at runtime.");
    }

    private static string MetricLabel(string raw) => raw switch
    {
        "throughput_mbps" => "throughput",
        "latency_ms" => "latency",
        _ => raw,
    };

    private static string Num(double? v) =>
        v is { } d ? d.ToString("0.##", CultureInfo.InvariantCulture) : "—";
}
