using System.Globalization;
using Networker.ControlPlane.Endpoints;

namespace Networker.ControlPlane.Reports.Documents;

/// <summary>
/// The data a single test-run report renders — the run header plus its
/// per-attempt probe rows (<see cref="AttemptView"/>, the same shape
/// <c>GET /api/v2/test-runs/{id}/attempts</c> returns). Assembled by the
/// endpoint; <see cref="RunReportDocument.Build"/> is a pure function of it so
/// the layout is unit-testable without a DB.
/// </summary>
public sealed record RunReportInput(
    Guid RunId,
    string ProjectId,
    string ConfigName,
    string? Target,
    string Status,
    DateTime? StartedAt,
    DateTime? FinishedAt,
    int SuccessCount,
    int FailureCount,
    string? ErrorMessage,
    IReadOnlyList<AttemptView> Attempts,
    ReportRunInfra? Infra = null);

/// <summary>
/// Builds the "Test Run Report": a summary KPI strip, a per-protocol latency
/// breakdown, median phase timings (DNS/TCP/TLS/TTFB), and a capped per-attempt
/// table. Pure — no I/O.
/// </summary>
public static class RunReportDocument
{
    /// <summary>Per-attempt rows beyond this are summarised, not listed, to keep
    /// the document readable for large runs.</summary>
    public const int MaxAttemptRows = 100;

    public static ReportDocument Build(RunReportInput run)
    {
        var sections = new List<ReportSection>();

        var total = run.Attempts.Count;
        var ok = run.Attempts.Count(a => a.Success);
        var failed = total - ok;
        // Fall back to the run's own counters when no probe rows were persisted
        // (benchmark-style runs, DB-less testers).
        var totalForRate = total > 0 ? total : run.SuccessCount + run.FailureCount;
        var okForRate = total > 0 ? ok : run.SuccessCount;
        var successRate = totalForRate > 0 ? 100.0 * okForRate / totalForRate : (double?)null;

        // ── Summary ──
        var summary = new List<ReportBlock>
        {
            new MetricsBlock(
                new Metric("Attempts", totalForRate.ToString(CultureInfo.InvariantCulture)),
                new Metric("Succeeded", okForRate.ToString(CultureInfo.InvariantCulture), ReportTone.Good),
                new Metric("Failed", (totalForRate - okForRate).ToString(CultureInfo.InvariantCulture),
                    (totalForRate - okForRate) > 0 ? ReportTone.Bad : ReportTone.Neutral),
                new Metric("Success rate", successRate is { } r ? r.ToString("0.#", CultureInfo.InvariantCulture) + "%" : "—",
                    RateTone(successRate))),
        };
        summary.Add(VerdictCallout(run, totalForRate, okForRate));
        if (!string.IsNullOrWhiteSpace(run.ErrorMessage))
        {
            summary.Add(new CalloutBlock("Run error: " + run.ErrorMessage, ReportTone.Bad));
        }
        sections.Add(new ReportSection("Summary", summary));

        // ── By protocol ──
        if (total > 0)
        {
            var envelope = InfraEnvelopeBlocks(run);
            if (envelope is not null)
            {
                sections.Add(new ReportSection("Infrastructure envelope", envelope));
            }

            sections.Add(new ReportSection("Latency by protocol", ByProtocolBlocks(run.Attempts)));

            var throughput = ThroughputBlocks(run.Attempts);
            if (throughput is not null)
            {
                sections.Add(new ReportSection("Throughput", throughput));
            }

            var phases = PhaseTimings(run.Attempts);
            if (phases is not null)
            {
                sections.Add(new ReportSection("Median phase timings", phases));
            }

            sections.Add(new ReportSection("Attempts", AttemptsTable(run.Attempts)));
        }
        else
        {
            sections.Add(new ReportSection("Attempts",
                new ProseBlock("No per-attempt probe rows were persisted for this run "
                    + "(benchmark-style run, or a tester without result-schema access).")));
        }

        var subtitle = run.Target is { Length: > 0 } t ? $"{run.ConfigName} → {t}" : run.ConfigName;

        var meta = new List<ReportMeta>
        {
            new("Run", ShortId(run.RunId)),
            new("Project", run.ProjectId),
            new("Status", run.Status),
        };
        if (run.StartedAt is { } started)
        {
            meta.Add(new ReportMeta("Started", started.ToString("yyyy-MM-dd HH:mm 'UTC'", CultureInfo.InvariantCulture)));
        }
        var duration = Duration(run.StartedAt, run.FinishedAt);
        if (duration is not null)
        {
            meta.Add(new ReportMeta("Duration", duration));
        }

        return new ReportDocument(
            Title: "Test Run Report",
            Subtitle: subtitle,
            GeneratedAt: DateTime.UtcNow,
            Meta: meta,
            Sections: sections,
            FooterNote: $"Generated by {ReportBranding.ProductName}. Latency percentiles are computed "
                + "over the attempts in this run only.");
    }

    private static CalloutBlock VerdictCallout(RunReportInput run, int total, int ok)
    {
        if (total == 0)
        {
            return new CalloutBlock("Run completed with no recorded attempts.", ReportTone.Neutral);
        }
        var failed = total - ok;
        return failed == 0
            ? new CalloutBlock($"All {total} attempts succeeded.", ReportTone.Good)
            : new CalloutBlock($"{failed} of {total} attempts failed.", ReportTone.Bad);
    }

    /// <summary>Modes whose primary "duration" is the probe's own runtime, not
    /// a latency (mthroughput's ramp, rpm's load cycle) — they'd read as absurd
    /// multi-second latencies and stretch the shared axis.</summary>
    private static readonly string[] NonLatencyProtocols = ["mthroughput", "rpm", "responsiveness"];

    private static readonly string[] ThroughputProtocols =
        ["download", "webdownload", "udpdownload", "upload", "webupload", "udpupload"];

    private static bool IsThroughput(string protocol) =>
        ThroughputProtocols.Contains(protocol, StringComparer.OrdinalIgnoreCase);

    /// <summary>Row key: throughput modes get one row PER PAYLOAD SIZE
    /// ("DOWNLOAD · 100 MB") — a single row would mix a 1 KB transfer with a
    /// 100 MB one and show payload size as fake latency spread (the dashboard's
    /// v0.28.121 box-plot fix, mirrored).</summary>
    private static string RowLabel(AttemptView a) =>
        IsThroughput(a.Protocol) && a.Http?.PayloadBytes is { } pb
            ? $"{a.Protocol.ToUpperInvariant()} · {Bytes(pb)}"
            : a.Protocol.ToUpperInvariant();

    private static IReadOnlyList<ReportBlock> ByProtocolBlocks(IReadOnlyList<AttemptView> attempts)
    {
        var agg = attempts
            .GroupBy(RowLabel, StringComparer.Ordinal)
            .Select(g =>
            {
                // Latency stats over SUCCESSFUL attempts only — a failed
                // attempt's duration is its timeout (ping on an Azure public
                // IP reads 50 s), which is failure evidence, not latency.
                var lat = g.Where(a => a.Success)
                    .Select(PrimaryLatencyMs)
                    .Where(x => x is not null)
                    .Select(x => x!.Value)
                    .ToList();
                return new
                {
                    Name = g.Key,
                    Protocol = g.First().Protocol,
                    PayloadBytes = g.First().Http?.PayloadBytes ?? -1,
                    Count = g.Count(),
                    Ok = g.Count(a => a.Success),
                    Min = lat.Count > 0 ? lat.Min() : (double?)null,
                    P25 = Percentile(lat, 0.25),
                    P50 = Percentile(lat, 0.50),
                    P75 = Percentile(lat, 0.75),
                    P95 = Percentile(lat, 0.95),
                    Max = lat.Count > 0 ? lat.Max() : (double?)null,
                };
            })
            .OrderBy(a => a.Protocol, StringComparer.OrdinalIgnoreCase)
            .ThenBy(a => a.PayloadBytes)
            .ToList();

        var rows = agg
            .Select(a => (IReadOnlyList<string>)new[]
            {
                a.Name,
                a.Count.ToString(CultureInfo.InvariantCulture),
                a.Ok.ToString(CultureInfo.InvariantCulture),
                (a.Count - a.Ok).ToString(CultureInfo.InvariantCulture),
                Ms(a.P50),
                Ms(a.P95),
            })
            .ToList();

        var table = new TableBlock(
            Headers: new[] { "Protocol", "Attempts", "OK", "Err", "p50", "p95" },
            Rows: rows,
            Aligns: new[]
            {
                ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right,
                ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
            });

        // A latency distribution ("candle" / box-plot) per row — min→max
        // whisker, p25→p75 box, median tick, p95 tail marker, on a LOG axis
        // (values legitimately span µs probes to second-scale 100 MB
        // transfers; linear crushed everything small into slivers). Probe-
        // duration modes (mthroughput/rpm) are excluded — their "latency" is
        // the probe's own runtime.
        var candles = agg
            .Where(a => a.P50 is not null
                        && !NonLatencyProtocols.Contains(a.Protocol, StringComparer.OrdinalIgnoreCase))
            .Select(a => new CandlePoint(a.Name, a.Min, a.P25, a.P50, a.P75, a.P95, a.Max, ReportTone.Info))
            .ToList();

        return candles.Count > 0
            ? new ReportBlock[]
            {
                new CandleBlock(
                    "Latency distribution (log scale · successful attempts · throughput modes shown as transfer time per payload)",
                    candles, "ms", LogScale: true),
                table,
            }
            : new ReportBlock[] { table };
    }

    /// <summary>Throughput by direction × payload (MB/s, successful attempts) —
    /// the numbers the latency view intentionally does not carry, plus the
    /// per-direction measurement note.</summary>
    private static IReadOnlyList<ReportBlock>? ThroughputBlocks(IReadOnlyList<AttemptView> attempts)
    {
        var rows = attempts
            .Where(a => a.Success && IsThroughput(a.Protocol)
                        && a.Http?.ThroughputMbps is not null && a.Http?.PayloadBytes is not null)
            .GroupBy(a => (Protocol: a.Protocol.ToUpperInvariant(), Payload: a.Http!.PayloadBytes!.Value))
            .OrderBy(g => g.Key.Protocol, StringComparer.Ordinal)
            .ThenBy(g => g.Key.Payload)
            .Select(g =>
            {
                var v = g.Select(a => a.Http!.ThroughputMbps!.Value).ToList();
                return (IReadOnlyList<string>)new[]
                {
                    g.Key.Protocol,
                    Bytes(g.Key.Payload),
                    g.Count().ToString(CultureInfo.InvariantCulture),
                    MBs(v.Min()),
                    MBs(Percentile(v, 0.50)!.Value),
                    MBs(Percentile(v, 0.95)!.Value),
                    MBs(v.Max()),
                };
            })
            .ToList();

        if (rows.Count == 0)
        {
            return null;
        }

        return new ReportBlock[]
        {
            new TableBlock(
                Headers: new[] { "Direction", "Payload", "N", "Min", "p50", "p95", "Max" },
                Rows: rows,
                Aligns: new[]
                {
                    ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
                    ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
                }),
            new ProseBlock(
                "Throughput is measured per direction — download over the body-receive window, upload "
                + "over the send window (cross-checked against the server's Server-Timing clock). Upload "
                + "and download legitimately differ on asymmetric paths: cloud VMs cap egress. Small "
                + "payloads reflect TCP slow-start burst, not steady-state bandwidth."),
        };
    }

    /// <summary>The infrastructure envelope: hardware identity, per-direction
    /// expected-vs-measured with verdicts (measured multi-stream ceiling when
    /// the run includes mthroughput), the CPU-idle callout, and right-sizing
    /// suggestions. Mirrors the dashboard panel via the shared
    /// <see cref="RunInfraAssessment"/> port.</summary>
    private static IReadOnlyList<ReportBlock>? InfraEnvelopeBlocks(RunReportInput run)
    {
        var infra = run.Infra;
        if (infra is null || (infra.Runner is null && infra.Target is null))
        {
            return null;
        }

        var blocks = new List<ReportBlock>();

        var idRows = new List<IReadOnlyList<string>>();
        void SideRow(string label, ReportInfraSide? s)
        {
            if (s is null)
            {
                return;
            }
            var hw = s.Specs is { } sp
                ? $"{sp.Vcpus} vCPU / {sp.MemoryGb.ToString("0.#", CultureInfo.InvariantCulture)} GB · "
                  + $"{(sp.Confidence == "estimated" ? "~" : "")}{RunInfraAssessment.FmtMbps(sp.EgressMbps)} egress "
                  + $"({(sp.Confidence == "documented" ? "doc" : "est")})"
                  + (sp.AcceleratedNetworking ? "" : " · no accel-net")
                : "no spec in catalog";
            idRows.Add(new[]
            {
                label,
                s.VmSize ?? "unknown size",
                s.Cloud + (s.Region is { Length: > 0 } r ? " " + r : ""),
                hw,
            });
        }
        SideRow("runner", infra.Runner);
        SideRow("target", infra.Target);
        blocks.Add(new TableBlock(
            Headers: new[] { "Side", "VM size", "Cloud", "Hardware / expected egress" },
            Rows: idRows,
            Aligns: new[] { ColumnAlign.Left, ColumnAlign.Left, ColumnAlign.Left, ColumnAlign.Left }));

        var assessments = RunInfraAssessment.Assess(run.Attempts, infra);
        if (assessments.Count > 0)
        {
            blocks.Add(new TableBlock(
                Headers: new[] { "Direction", "Measured", "Ceiling", "Utilization", "Verdict" },
                Rows: assessments.Select(a => (IReadOnlyList<string>)new[]
                {
                    a.Direction,
                    RunInfraAssessment.FmtMbps(a.MeasuredMbps) + $" @ {Bytes(a.PayloadBytes)}",
                    a.ExpectedMbps is { } e
                        ? $"{(a.Confidence == "estimated" ? "~" : "")}{RunInfraAssessment.FmtMbps(e)}"
                          + $" ({a.Confidence})"
                        : "—",
                    a.Utilization is { } u
                        ? Math.Round(u * 100).ToString("0", CultureInfo.InvariantCulture) + "%"
                        : "—",
                    a.Verdict,
                }).ToList(),
                Aligns: new[]
                {
                    ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right,
                    ColumnAlign.Right, ColumnAlign.Left,
                }));

            var cpuIdle = infra is { CpuCores: > 0, PeakLoad1m: { } load }
                && load < infra.CpuCores.Value * 0.5;
            if (cpuIdle && assessments.Any(a => a.Verdict == "network-bound"))
            {
                blocks.Add(new CalloutBlock(
                    $"Runner CPU stayed idle (peak load {infra.PeakLoad1m!.Value.ToString("0.00", CultureInfo.InvariantCulture)} "
                    + $"/ {infra.CpuCores} cores) while a direction sat at its egress cap — the network, "
                    + "not compute, is the binding constraint of this infrastructure.",
                    ReportTone.Info));
            }

            foreach (var s in RunInfraAssessment.Advise(assessments, infra))
            {
                blocks.Add(new CalloutBlock($"{s.Kind}: {s.Text}",
                    s.Kind == "upsize" ? ReportTone.Info : ReportTone.Good));
            }
        }

        blocks.Add(new ProseBlock(
            "Ceiling = the sending side's egress expectation per the VM-size catalog (doc = provider "
            + "size table · est = bandwidth not guaranteed by the provider), superseded by the measured "
            + "multi-stream capacity when the run includes the Multi-Conn (mthroughput) mode. "
            + "Steady-state = p50 at the largest payload."));

        return blocks;
    }

    private static IReadOnlyList<ReportBlock>? PhaseTimings(IReadOnlyList<AttemptView> attempts)
    {
        var dns = Median(attempts.Select(a => a.Dns?.DurationMs));
        var tcp = Median(attempts.Select(a => a.Tcp?.ConnectDurationMs));
        var tls = Median(attempts.Select(a => a.Tls?.HandshakeDurationMs));
        var ttfb = Median(attempts.Select(a => a.Http?.TtfbMs));
        var server = Median(attempts.Select(a => a.ServerTiming?.TotalServerMs));

        var rows = new List<IReadOnlyList<string>>();
        void Add(string phase, double? v)
        {
            if (v is not null)
            {
                rows.Add(new[] { phase, Ms(v) });
            }
        }
        Add("DNS resolve", dns);
        Add("TCP connect", tcp);
        Add("TLS handshake", tls);
        Add("Time to first byte", ttfb);
        Add("Server processing", server);

        if (rows.Count == 0)
        {
            return null;
        }

        return new ReportBlock[]
        {
            new TableBlock(
                Headers: new[] { "Phase", "Median" },
                Rows: rows,
                Aligns: new[] { ColumnAlign.Left, ColumnAlign.Right }),
        };
    }

    private static TableBlock AttemptsTable(IReadOnlyList<AttemptView> attempts)
    {
        var shown = attempts
            .OrderBy(a => a.SequenceNum)
            .Take(MaxAttemptRows)
            .Select(a => (IReadOnlyList<string>)new[]
            {
                a.SequenceNum.ToString(CultureInfo.InvariantCulture),
                a.Protocol.ToUpperInvariant(),
                a.Success ? "ok" : "fail",
                Ms(PrimaryLatencyMs(a)),
                Detail(a),
            })
            .ToList();

        return new TableBlock(
            Headers: new[] { "#", "Protocol", "Result", "Latency", "Detail" },
            Rows: shown,
            Aligns: new[]
            {
                ColumnAlign.Right, ColumnAlign.Left, ColumnAlign.Left,
                ColumnAlign.Right, ColumnAlign.Left,
            });
    }

    /// <summary>A short human detail for the attempt row — status/error/key metric.</summary>
    private static string Detail(AttemptView a)
    {
        if (!a.Success && !string.IsNullOrWhiteSpace(a.ErrorMessage))
        {
            return Truncate(a.ErrorMessage!, 60);
        }
        if (a.Mthroughput is { } mt)
        {
            var caps = new List<string>();
            if (mt.CapacityDownMbps is { } cd)
            {
                caps.Add($"↓ {MBs(cd)} ({mt.ConnsDown} conns)");
            }
            if (mt.CapacityUpMbps is { } cu)
            {
                caps.Add($"↑ {MBs(cu)}" + (mt.ConnsUp is { } cc ? $" ({cc} conns)" : ""));
            }
            if (caps.Count > 0)
            {
                return "capacity " + string.Join(" · ", caps);
            }
        }
        if (a.Http is { } h)
        {
            var parts = new List<string> { "HTTP " + h.StatusCode };
            if (!string.IsNullOrEmpty(h.NegotiatedVersion))
            {
                parts.Add(h.NegotiatedVersion);
            }
            // ThroughputMbps carries MB/s (decimal) despite the field name —
            // mirrors the tester struct; the old " Mbps" label was a units bug.
            if (h.ThroughputMbps is { } mbs)
            {
                parts.Add(MBs(mbs));
            }
            return string.Join(" · ", parts);
        }
        if (a.Udp is { } u)
        {
            return $"loss {u.LossPercent.ToString("0.#", CultureInfo.InvariantCulture)}% · jitter {Ms(u.JitterMs)}";
        }
        if (a.Tls is { } t)
        {
            return t.ProtocolVersion + (t.AlpnNegotiated is { Length: > 0 } alpn ? " · " + alpn : "");
        }
        return "";
    }

    // ── metric helpers ──────────────────────────────────────────────────────

    /// <summary>The attempt's representative latency: its protocol's primary
    /// phase, falling back to the wall time.</summary>
    private static double? PrimaryLatencyMs(AttemptView a) =>
        a.Http?.TotalDurationMs
        ?? a.Udp?.RttAvgMs
        ?? a.Tls?.HandshakeDurationMs
        ?? a.Dns?.DurationMs
        ?? a.Tcp?.ConnectDurationMs
        ?? WallMs(a);

    private static double? WallMs(AttemptView a) =>
        a.FinishedAt is { } f ? (f - a.StartedAt).TotalMilliseconds : null;

    private static double? Median(IEnumerable<double?> values) =>
        Percentile(values.Where(v => v is not null).Select(v => v!.Value).ToList(), 0.50);

    /// <summary>Linear-interpolated percentile of a sample (q in [0,1]); null if
    /// empty. Matches the PERCENTILE_CONT the SQL reports use.</summary>
    private static double? Percentile(IReadOnlyList<double> values, double q)
    {
        if (values.Count == 0)
        {
            return null;
        }
        var sorted = values.OrderBy(x => x).ToList();
        if (sorted.Count == 1)
        {
            return sorted[0];
        }
        var pos = q * (sorted.Count - 1);
        var lo = (int)Math.Floor(pos);
        var hi = (int)Math.Ceiling(pos);
        var frac = pos - lo;
        return sorted[lo] + (sorted[hi] - sorted[lo]) * frac;
    }

    private static ReportTone RateTone(double? rate) => rate switch
    {
        null => ReportTone.Neutral,
        >= 99.5 => ReportTone.Good,
        >= 95 => ReportTone.Warn,
        _ => ReportTone.Bad,
    };

    private static string Ms(double? v) =>
        v is { } d ? d.ToString(d >= 100 ? "0" : "0.0", CultureInfo.InvariantCulture) + " ms" : "—";

    /// <summary>MB/s formatting for http.throughput_mbps (which carries
    /// decimal megabytes/second, matching the tester struct).</summary>
    private static string MBs(double v) =>
        v.ToString(v >= 100 ? "0" : "0.#", CultureInfo.InvariantCulture) + " MB/s";

    private static string Bytes(long bytes) => bytes switch
    {
        >= 1024L * 1024 * 1024 => (bytes / (1024.0 * 1024 * 1024)).ToString("0.#", CultureInfo.InvariantCulture) + " GB",
        >= 1024L * 1024 => (bytes / (1024.0 * 1024)).ToString("0.#", CultureInfo.InvariantCulture) + " MB",
        >= 1024L => (bytes / 1024.0).ToString("0.#", CultureInfo.InvariantCulture) + " KB",
        _ => bytes.ToString(CultureInfo.InvariantCulture) + " B",
    };

    private static string? Duration(DateTime? start, DateTime? end)
    {
        if (start is not { } s || end is not { } e || e < s)
        {
            return null;
        }
        var span = e - s;
        return span.TotalSeconds < 60
            ? span.TotalSeconds.ToString("0.0", CultureInfo.InvariantCulture) + " s"
            : $"{(int)span.TotalMinutes}m {span.Seconds}s";
    }

    private static string ShortId(Guid id) => id.ToString("N")[..8];

    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";
}
