using System.Globalization;
using Networker.ControlPlane.Endpoints;

namespace Networker.ControlPlane.Reports.Documents;

/// <summary>
/// The data a single test-run report renders — the run header plus its
/// per-attempt probe rows (<see cref="AttemptView"/>, the same shape
/// <c>GET /api/v2/test-runs/{id}/attempts</c> returns). Assembled by the
/// endpoint; <see cref="RunReportDocument.Build"/> is a pure function of it so
/// the layout is unit-testable without a DB.
/// </summary>
public sealed record RunReportInput(
    Guid RunId,
    string ProjectId,
    string ConfigName,
    string? Target,
    string Status,
    DateTime? StartedAt,
    DateTime? FinishedAt,
    int SuccessCount,
    int FailureCount,
    string? ErrorMessage,
    IReadOnlyList<AttemptView> Attempts);

/// <summary>
/// Builds the "Test Run Report": a summary KPI strip, a per-protocol latency
/// breakdown, median phase timings (DNS/TCP/TLS/TTFB), and a capped per-attempt
/// table. Pure — no I/O.
/// </summary>
public static class RunReportDocument
{
    /// <summary>Per-attempt rows beyond this are summarised, not listed, to keep
    /// the document readable for large runs.</summary>
    public const int MaxAttemptRows = 100;

    public static ReportDocument Build(RunReportInput run)
    {
        var sections = new List<ReportSection>();

        var total = run.Attempts.Count;
        var ok = run.Attempts.Count(a => a.Success);
        var failed = total - ok;
        // Fall back to the run's own counters when no probe rows were persisted
        // (benchmark-style runs, DB-less testers).
        var totalForRate = total > 0 ? total : run.SuccessCount + run.FailureCount;
        var okForRate = total > 0 ? ok : run.SuccessCount;
        var successRate = totalForRate > 0 ? 100.0 * okForRate / totalForRate : (double?)null;

        // ── Summary ──
        var summary = new List<ReportBlock>
        {
            new MetricsBlock(
                new Metric("Attempts", totalForRate.ToString(CultureInfo.InvariantCulture)),
                new Metric("Succeeded", okForRate.ToString(CultureInfo.InvariantCulture), ReportTone.Good),
                new Metric("Failed", (totalForRate - okForRate).ToString(CultureInfo.InvariantCulture),
                    (totalForRate - okForRate) > 0 ? ReportTone.Bad : ReportTone.Neutral),
                new Metric("Success rate", successRate is { } r ? r.ToString("0.#", CultureInfo.InvariantCulture) + "%" : "—",
                    RateTone(successRate))),
        };
        summary.Add(VerdictCallout(run, totalForRate, okForRate));
        if (!string.IsNullOrWhiteSpace(run.ErrorMessage))
        {
            summary.Add(new CalloutBlock("Run error: " + run.ErrorMessage, ReportTone.Bad));
        }
        sections.Add(new ReportSection("Summary", summary));

        // ── By protocol ──
        if (total > 0)
        {
            sections.Add(new ReportSection("Latency by protocol", ByProtocolBlocks(run.Attempts)));

            var phases = PhaseTimings(run.Attempts);
            if (phases is not null)
            {
                sections.Add(new ReportSection("Median phase timings", phases));
            }

            sections.Add(new ReportSection("Attempts", AttemptsTable(run.Attempts)));
        }
        else
        {
            sections.Add(new ReportSection("Attempts",
                new ProseBlock("No per-attempt probe rows were persisted for this run "
                    + "(benchmark-style run, or a tester without result-schema access).")));
        }

        var subtitle = run.Target is { Length: > 0 } t ? $"{run.ConfigName} → {t}" : run.ConfigName;

        var meta = new List<ReportMeta>
        {
            new("Run", ShortId(run.RunId)),
            new("Project", run.ProjectId),
            new("Status", run.Status),
        };
        if (run.StartedAt is { } started)
        {
            meta.Add(new ReportMeta("Started", started.ToString("yyyy-MM-dd HH:mm 'UTC'", CultureInfo.InvariantCulture)));
        }
        var duration = Duration(run.StartedAt, run.FinishedAt);
        if (duration is not null)
        {
            meta.Add(new ReportMeta("Duration", duration));
        }

        return new ReportDocument(
            Title: "Test Run Report",
            Subtitle: subtitle,
            GeneratedAt: DateTime.UtcNow,
            Meta: meta,
            Sections: sections,
            FooterNote: $"Generated by {ReportBranding.ProductName}. Latency percentiles are computed "
                + "over the attempts in this run only.");
    }

    private static CalloutBlock VerdictCallout(RunReportInput run, int total, int ok)
    {
        if (total == 0)
        {
            return new CalloutBlock("Run completed with no recorded attempts.", ReportTone.Neutral);
        }
        var failed = total - ok;
        return failed == 0
            ? new CalloutBlock($"All {total} attempts succeeded.", ReportTone.Good)
            : new CalloutBlock($"{failed} of {total} attempts failed.", ReportTone.Bad);
    }

    private static IReadOnlyList<ReportBlock> ByProtocolBlocks(IReadOnlyList<AttemptView> attempts)
    {
        var agg = attempts
            .GroupBy(a => a.Protocol, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g =>
            {
                var lat = g.Select(PrimaryLatencyMs).Where(x => x is not null).Select(x => x!.Value).ToList();
                return new
                {
                    Name = g.Key.ToUpperInvariant(),
                    Count = g.Count(),
                    Ok = g.Count(a => a.Success),
                    Min = lat.Count > 0 ? lat.Min() : (double?)null,
                    P25 = Percentile(lat, 0.25),
                    P50 = Percentile(lat, 0.50),
                    P75 = Percentile(lat, 0.75),
                    P95 = Percentile(lat, 0.95),
                    Max = lat.Count > 0 ? lat.Max() : (double?)null,
                };
            })
            .ToList();

        var rows = agg
            .Select(a => (IReadOnlyList<string>)new[]
            {
                a.Name,
                a.Count.ToString(CultureInfo.InvariantCulture),
                a.Ok.ToString(CultureInfo.InvariantCulture),
                (a.Count - a.Ok).ToString(CultureInfo.InvariantCulture),
                Ms(a.P50),
                Ms(a.P95),
            })
            .ToList();

        var table = new TableBlock(
            Headers: new[] { "Protocol", "Attempts", "OK", "Err", "p50", "p95" },
            Rows: rows,
            Aligns: new[]
            {
                ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right,
                ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right,
            });

        // A latency distribution ("candle" / box-plot) per protocol — min→max
        // whisker, p25→p75 box, median tick, p95 tail marker. Latency is a
        // distribution; the tail is what diagnostics care about, so this beats
        // a single-value bar. Only protocols with a measured latency appear.
        var candles = agg
            .Where(a => a.P50 is not null)
            .Select(a => new CandlePoint(a.Name, a.Min, a.P25, a.P50, a.P75, a.P95, a.Max, ReportTone.Info))
            .ToList();

        return candles.Count > 0
            ? new ReportBlock[] { new CandleBlock("Latency distribution by protocol", candles, "ms"), table }
            : new ReportBlock[] { table };
    }

    private static IReadOnlyList<ReportBlock>? PhaseTimings(IReadOnlyList<AttemptView> attempts)
    {
        var dns = Median(attempts.Select(a => a.Dns?.DurationMs));
        var tcp = Median(attempts.Select(a => a.Tcp?.ConnectDurationMs));
        var tls = Median(attempts.Select(a => a.Tls?.HandshakeDurationMs));
        var ttfb = Median(attempts.Select(a => a.Http?.TtfbMs));
        var server = Median(attempts.Select(a => a.ServerTiming?.TotalServerMs));

        var rows = new List<IReadOnlyList<string>>();
        void Add(string phase, double? v)
        {
            if (v is not null)
            {
                rows.Add(new[] { phase, Ms(v) });
            }
        }
        Add("DNS resolve", dns);
        Add("TCP connect", tcp);
        Add("TLS handshake", tls);
        Add("Time to first byte", ttfb);
        Add("Server processing", server);

        if (rows.Count == 0)
        {
            return null;
        }

        return new ReportBlock[]
        {
            new TableBlock(
                Headers: new[] { "Phase", "Median" },
                Rows: rows,
                Aligns: new[] { ColumnAlign.Left, ColumnAlign.Right }),
        };
    }

    private static TableBlock AttemptsTable(IReadOnlyList<AttemptView> attempts)
    {
        var shown = attempts
            .OrderBy(a => a.SequenceNum)
            .Take(MaxAttemptRows)
            .Select(a => (IReadOnlyList<string>)new[]
            {
                a.SequenceNum.ToString(CultureInfo.InvariantCulture),
                a.Protocol.ToUpperInvariant(),
                a.Success ? "ok" : "fail",
                Ms(PrimaryLatencyMs(a)),
                Detail(a),
            })
            .ToList();

        return new TableBlock(
            Headers: new[] { "#", "Protocol", "Result", "Latency", "Detail" },
            Rows: shown,
            Aligns: new[]
            {
                ColumnAlign.Right, ColumnAlign.Left, ColumnAlign.Left,
                ColumnAlign.Right, ColumnAlign.Left,
            });
    }

    /// <summary>A short human detail for the attempt row — status/error/key metric.</summary>
    private static string Detail(AttemptView a)
    {
        if (!a.Success && !string.IsNullOrWhiteSpace(a.ErrorMessage))
        {
            return Truncate(a.ErrorMessage!, 60);
        }
        if (a.Http is { } h)
        {
            var parts = new List<string> { "HTTP " + h.StatusCode };
            if (!string.IsNullOrEmpty(h.NegotiatedVersion))
            {
                parts.Add(h.NegotiatedVersion);
            }
            if (h.ThroughputMbps is { } mbps)
            {
                parts.Add(mbps.ToString("0.#", CultureInfo.InvariantCulture) + " Mbps");
            }
            return string.Join(" · ", parts);
        }
        if (a.Udp is { } u)
        {
            return $"loss {u.LossPercent.ToString("0.#", CultureInfo.InvariantCulture)}% · jitter {Ms(u.JitterMs)}";
        }
        if (a.Tls is { } t)
        {
            return t.ProtocolVersion + (t.AlpnNegotiated is { Length: > 0 } alpn ? " · " + alpn : "");
        }
        return "";
    }

    // ── metric helpers ──────────────────────────────────────────────────────

    /// <summary>The attempt's representative latency: its protocol's primary
    /// phase, falling back to the wall time.</summary>
    private static double? PrimaryLatencyMs(AttemptView a) =>
        a.Http?.TotalDurationMs
        ?? a.Udp?.RttAvgMs
        ?? a.Tls?.HandshakeDurationMs
        ?? a.Dns?.DurationMs
        ?? a.Tcp?.ConnectDurationMs
        ?? WallMs(a);

    private static double? WallMs(AttemptView a) =>
        a.FinishedAt is { } f ? (f - a.StartedAt).TotalMilliseconds : null;

    private static double? Median(IEnumerable<double?> values) =>
        Percentile(values.Where(v => v is not null).Select(v => v!.Value).ToList(), 0.50);

    /// <summary>Linear-interpolated percentile of a sample (q in [0,1]); null if
    /// empty. Matches the PERCENTILE_CONT the SQL reports use.</summary>
    private static double? Percentile(IReadOnlyList<double> values, double q)
    {
        if (values.Count == 0)
        {
            return null;
        }
        var sorted = values.OrderBy(x => x).ToList();
        if (sorted.Count == 1)
        {
            return sorted[0];
        }
        var pos = q * (sorted.Count - 1);
        var lo = (int)Math.Floor(pos);
        var hi = (int)Math.Ceiling(pos);
        var frac = pos - lo;
        return sorted[lo] + (sorted[hi] - sorted[lo]) * frac;
    }

    private static ReportTone RateTone(double? rate) => rate switch
    {
        null => ReportTone.Neutral,
        >= 99.5 => ReportTone.Good,
        >= 95 => ReportTone.Warn,
        _ => ReportTone.Bad,
    };

    private static string Ms(double? v) =>
        v is { } d ? d.ToString(d >= 100 ? "0" : "0.0", CultureInfo.InvariantCulture) + " ms" : "—";

    private static string? Duration(DateTime? start, DateTime? end)
    {
        if (start is not { } s || end is not { } e || e < s)
        {
            return null;
        }
        var span = e - s;
        return span.TotalSeconds < 60
            ? span.TotalSeconds.ToString("0.0", CultureInfo.InvariantCulture) + " s"
            : $"{(int)span.TotalMinutes}m {span.Seconds}s";
    }

    private static string ShortId(Guid id) => id.ToString("N")[..8];

    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";
}
