using System.Text;
using Networker.ControlPlane.Endpoints;
using Networker.ControlPlane.Reports;
using Networker.ControlPlane.Reports.Documents;

namespace Networker.ControlPlane.Tests;

/// <summary>
/// Covers the report-export engine: the exporters (Markdown / HTML / DOCX) over
/// a document exercising every block type, and the three builders. When the
/// <c>REPORT_SMOKE_DIR</c> env var is set, each exporter's output is also
/// written there for eyeball/PDF inspection (no-op in CI).
/// </summary>
public class ReportDocumentTests
{
    private static ReportDocument SampleDoc() => new(
        Title: "Test Run Report",
        Subtitle: "prod-http3-sweep → api.acme.com",
        GeneratedAt: new DateTime(2026, 7, 28, 14, 3, 0, DateTimeKind.Utc),
        Meta: new[]
        {
            new ReportMeta("Run", "a1b2c3d4"),
            new ReportMeta("Project", "acme"),
            new ReportMeta("Status", "completed"),
        },
        Sections: new[]
        {
            new ReportSection("Summary",
                new MetricsBlock(
                    new Metric("Attempts", "300"),
                    new Metric("Succeeded", "299", ReportTone.Good),
                    new Metric("Failed", "1", ReportTone.Bad),
                    new Metric("Success rate", "99.7%", ReportTone.Good)),
                new CalloutBlock("1 of 300 attempts failed.", ReportTone.Bad)),
            new ReportSection("Latency by protocol",
                new CandleBlock("Latency distribution by protocol", new[]
                {
                    new CandlePoint("HTTP2", 40, 72, 98, 150, 201, 260, ReportTone.Info),
                    new CandlePoint("HTTP3", 28, 55, 71, 110, 150, 190, ReportTone.Info),
                }, "ms"),
                new ChartBlock("p95 latency by protocol", new[]
                {
                    new ChartPoint("HTTP2", 201, "201 ms", ReportTone.Info),
                    new ChartPoint("HTTP3", 150, "150 ms", ReportTone.Info),
                }),
                new TableBlock(
                    new[] { "Protocol", "Attempts", "OK", "p50", "p95" },
                    new IReadOnlyList<string>[]
                    {
                        new[] { "HTTP2", "100", "100", "98.0 ms", "201 ms" },
                        new[] { "HTTP3", "100", "99", "71.0 ms", "150 ms" },
                    },
                    new[] { ColumnAlign.Left, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right, ColumnAlign.Right })),
        },
        FooterNote: "Generated by LagHound.");

    public static IEnumerable<object[]> Exporters()
    {
        yield return new object[] { new MarkdownReportExporter() };
        yield return new object[] { new HtmlReportExporter() };
        yield return new object[] { new DocxReportExporter() };
        yield return new object[] { new PdfReportExporter() };
    }

    [Theory]
    [MemberData(nameof(Exporters))]
    public void Exporter_produces_nonempty_output_with_sane_metadata(IReportExporter exporter)
    {
        var bytes = exporter.Render(SampleDoc());

        Assert.NotEmpty(bytes);
        Assert.False(string.IsNullOrWhiteSpace(exporter.ContentType));
        Assert.Matches("^[a-z0-9]+$", exporter.FileExtension);

        WriteSmokeArtifact(exporter, bytes);
    }

    [Fact]
    public void Markdown_contains_title_wordmark_and_table()
    {
        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(SampleDoc()));

        Assert.Contains("**LagHound**", md);
        Assert.Contains("# Test Run Report", md);
        Assert.Contains("| Protocol | Attempts | OK | p50 | p95 |", md);
        Assert.Contains("| HTTP2 | 100 | 100 | 98.0 ms | 201 ms |", md);
        // right-aligned columns get the ---: separator
        Assert.Contains(" ---: |", md);
    }

    [Fact]
    public void Html_is_self_contained_with_inline_logo_and_escaping()
    {
        var html = Encoding.UTF8.GetString(new HtmlReportExporter().Render(SampleDoc()));

        Assert.StartsWith("<!doctype html>", html);
        Assert.Contains("<svg", html);                    // inline wordmark
        Assert.Contains("#863bff", html);                 // brand purple in CSS
        // Self-contained: no external stylesheet/script/font/image fetches.
        // (The SVG's xmlns="http://www.w3.org/2000/svg" is a namespace, not a request.)
        Assert.DoesNotContain("<link", html);
        Assert.DoesNotContain("<script", html);
        Assert.DoesNotContain("src=\"http", html);
        Assert.DoesNotContain("@import", html);
        Assert.Contains("<table>", html);
    }

    [Fact]
    public void Html_escapes_html_metacharacters_in_content()
    {
        var doc = new ReportDocument("A <b>title</b> & more", null, DateTime.UtcNow,
            Array.Empty<ReportMeta>(),
            new[] { new ReportSection("S", new ProseBlock("1 < 2 && 3 > 2")) });

        var html = Encoding.UTF8.GetString(new HtmlReportExporter().Render(doc));

        Assert.Contains("A &lt;b&gt;title&lt;/b&gt; &amp; more", html);
        Assert.Contains("1 &lt; 2 &amp;&amp; 3 &gt; 2", html);
    }

    [Fact]
    public void Markdown_escapes_pipes_so_tables_dont_break()
    {
        var doc = new ReportDocument("T", null, DateTime.UtcNow, Array.Empty<ReportMeta>(),
            new[] { new ReportSection("S", new ProseBlock("a | b | c")) });

        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(doc));

        Assert.Contains("a \\| b \\| c", md);
    }

    [Fact]
    public void Html_renders_chart_as_inline_svg_bars()
    {
        var html = Encoding.UTF8.GetString(new HtmlReportExporter().Render(SampleDoc()));

        Assert.Contains("svg class=\"chart\"", html);
        Assert.Contains("p95 latency by protocol", html);
        Assert.Contains(ReportBranding.Cyan, html);   // info-tone bars use brand cyan
    }

    [Fact]
    public void Markdown_renders_chart_as_unicode_bars()
    {
        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(SampleDoc()));

        Assert.Contains("█", md);
        Assert.Contains("HTTP2", md);
    }

    [Fact]
    public void Html_renders_candle_as_svg_boxplot()
    {
        var html = Encoding.UTF8.GetString(new HtmlReportExporter().Render(SampleDoc()));

        Assert.Contains("svg class=\"chart candle\"", html);
        Assert.Contains("class=\"whisk\"", html);          // min→max whisker
        Assert.Contains("Latency distribution by protocol", html);
    }

    [Fact]
    public void Markdown_renders_candle_as_monospace_boxplot()
    {
        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(SampleDoc()));

        Assert.Contains("├", md);                          // whisker cap
        Assert.Contains("p95 201", md);                    // summary carries the tail
        Assert.Contains("max 260 ms", md);                 // unit appended once at the end
    }

    [Fact]
    public void CandleAscii_track_places_whisker_box_and_median()
    {
        var p = new CandlePoint("x", Min: 0, P25: 25, Median: 50, P75: 75, High: 100, P95: 90);
        var track = CandleAscii.Track(p, axisMax: 100);

        Assert.Equal(CandleAscii.Cells, track.Length);
        Assert.StartsWith("├", track);                     // min at axis start
        Assert.EndsWith("┤", track);                       // max at axis end
        Assert.Contains("█", track);                       // p25→p75 box
        Assert.Contains("┃", track);                       // median inside the box
    }

    [Fact]
    public void Chart_scales_bars_to_the_largest_value()
    {
        var chart = new ChartBlock("t", new[]
        {
            new ChartPoint("a", 50, "50"),
            new ChartPoint("b", 100, "100"),
        });

        Assert.Equal(100, chart.Max);
        Assert.Equal(0.5, chart.Fraction(50), 3);
        Assert.Equal(1.0, chart.Fraction(100), 3);
        Assert.Equal(1.0, chart.Fraction(200), 3);   // clamped
    }

    [Fact]
    public void Pdf_starts_with_the_pdf_magic_and_has_content()
    {
        var bytes = new PdfReportExporter().Render(SampleDoc());

        Assert.True(bytes.Length > 1000);
        Assert.Equal("%PDF-", Encoding.ASCII.GetString(bytes, 0, 5));
        // %%EOF trailer near the end.
        var tail = Encoding.ASCII.GetString(bytes, Math.Max(0, bytes.Length - 8), Math.Min(8, bytes.Length));
        Assert.Contains("%%EOF", tail);
    }

    [Fact]
    public void Docx_survives_ansi_and_xml_invalid_control_characters()
    {
        // Regression: a 2026-07-19 run's error_message carried raw ANSI SGR
        // codes ("\u001b[2m…") — ESC is not a legal XML char, so the DOCX
        // export 500'd in prod while MD/HTML/PDF tolerated it. The exporter
        // must sanitize rather than throw, whatever the content.
        var doc = new ReportDocument("T", null, DateTime.UtcNow, Array.Empty<ReportMeta>(),
            new[]
            {
                new ReportSection("S",
                    new CalloutBlock("Run error: [tester] \u001b[2m2026-07-19\u001b[0m \u001b[32mINFO\u001b[0m boom \u0000\u0001", ReportTone.Bad),
                    new ProseBlock("plain text stays intact")),
            });

        var bytes = new DocxReportExporter().Render(doc);   // must not throw

        Assert.Equal((byte)'P', bytes[0]);
        Assert.Equal((byte)'K', bytes[1]);
        // Inspect the actual XML part (raw zip bytes are deflate-compressed —
        // scanning THEM for 0x1b would be meaningless): the visible text
        // survives, the illegal characters do not.
        using var zip = new System.IO.Compression.ZipArchive(new MemoryStream(bytes));
        using var reader = new StreamReader(zip.GetEntry("word/document.xml")!.Open());
        var xml = reader.ReadToEnd();
        Assert.Contains("boom", xml);
        Assert.Contains("plain text stays intact", xml);
        Assert.DoesNotContain('\u001b', xml);
        Assert.DoesNotContain('\u0000', xml);
        Assert.DoesNotContain('\u0001', xml);
    }

    [Fact]
    public void RunReport_error_message_flows_ansi_free_when_prestripped()
    {
        // The endpoint strips ANSI before building (AnsiText.Strip, matching
        // /attempts); verify the stripped text flows through the render.
        var input = new RunReportInput(
            Guid.NewGuid(), "acme", "cfg", null, "failed", null, null,
            SuccessCount: 0, FailureCount: 1,
            ErrorMessage: Networker.ControlPlane.AnsiText.Strip("[tester] \u001b[2m2026-07-19\u001b[0m fatal: no route"),
            Attempts: Array.Empty<AttemptView>());

        var md = Encoding.UTF8.GetString(
            new MarkdownReportExporter().Render(RunReportDocument.Build(input)));

        Assert.Contains("fatal: no route", md);
        Assert.Equal(-1, md.IndexOf('\u001b'));
    }

    [Fact]
    public void Docx_is_a_valid_zip_package()
    {
        var bytes = new DocxReportExporter().Render(SampleDoc());

        // .docx is an OPC ZIP — first two bytes are 'P' 'K'.
        Assert.True(bytes.Length > 100);
        Assert.Equal((byte)'P', bytes[0]);
        Assert.Equal((byte)'K', bytes[1]);
    }

    [Fact]
    public void Resolver_returns_available_formats_and_rejects_unregistered()
    {
        var resolver = new ReportExporterResolver(new IReportExporter[]
        {
            new MarkdownReportExporter(), new HtmlReportExporter(), new DocxReportExporter(),
        });

        Assert.True(resolver.TryResolve(ReportFormat.Markdown, out _));
        Assert.False(resolver.TryResolve(ReportFormat.Pdf, out _));   // not registered in PR1
        Assert.Equal(new[] { "docx", "html", "markdown" }, resolver.AvailableDocumentFormats);
    }

    [Theory]
    [InlineData("md", ReportFormat.Markdown)]
    [InlineData("MARKDOWN", ReportFormat.Markdown)]
    [InlineData("html", ReportFormat.Html)]
    [InlineData("docx", ReportFormat.Docx)]
    [InlineData("pdf", ReportFormat.Pdf)]
    [InlineData("", ReportFormat.Json)]
    [InlineData(null, ReportFormat.Json)]
    public void Format_parse_accepts_known_values(string? input, ReportFormat expected)
    {
        Assert.True(ReportFormats.TryParse(input, out var fmt));
        Assert.Equal(expected, fmt);
    }

    [Fact]
    public void Format_parse_rejects_unknown()
    {
        Assert.False(ReportFormats.TryParse("xlsx", out _));
    }

    // ── builders ──────────────────────────────────────────────────────────────

    [Fact]
    public void RunReport_builds_summary_protocol_and_attempts()
    {
        var attempts = new[]
        {
            Attempt(1, "http2", true, http: new AttemptHttpView(200, "HTTP/2", 40, 98, 1024, 0, null, null)),
            Attempt(2, "http2", true, http: new AttemptHttpView(200, "HTTP/2", 44, 110, 1024, 0, null, null)),
            Attempt(3, "http3", false, error: "connection timed out"),
        };
        var input = new RunReportInput(
            Guid.NewGuid(), "acme", "prod-sweep", "api.acme.com", "completed",
            new DateTime(2026, 7, 28, 14, 0, 0, DateTimeKind.Utc),
            new DateTime(2026, 7, 28, 14, 0, 12, DateTimeKind.Utc),
            SuccessCount: 2, FailureCount: 1, ErrorMessage: null, Attempts: attempts);

        var doc = RunReportDocument.Build(input);

        Assert.Equal("Test Run Report", doc.Title);
        Assert.Contains(doc.Sections, s => s.Heading == "Latency by protocol");
        Assert.Contains(doc.Sections, s => s.Heading == "Attempts");
        // The failed attempt's error surfaces in the rendered markdown.
        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(doc));
        Assert.Contains("connection timed out", md);
        Assert.Contains("1 of 3 attempts failed.", md);
    }

    [Fact]
    public void RunReport_handles_a_run_with_no_attempts()
    {
        var input = new RunReportInput(
            Guid.NewGuid(), "acme", "bench", null, "completed", null, null,
            SuccessCount: 0, FailureCount: 0, ErrorMessage: null,
            Attempts: Array.Empty<AttemptView>());

        var doc = RunReportDocument.Build(input);

        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(doc));
        Assert.Contains("No per-attempt probe rows", md);
    }

    [Fact]
    public void AppNetwork_builder_maps_verdict_and_groups()
    {
        var report = new AppNetworkReport(
            GeneratedAt: DateTime.UtcNow,
            Formulas: new AppNetworkFormulas("server", "network", "split", "anomaly"),
            Mode: "sdkprobe",
            AttemptCount: 120,
            SplitAnomalyCount: 0,
            OverallVerdict: AppNetworkLogic.VerdictNetworkBound,
            OverallMainIssue: "network dominates",
            OverallMedianServerMs: 12.0,
            OverallMedianNetworkMs: 88.0,
            OverallMedianWallMs: 100.0,
            OverallServerRatio: 0.12,
            Groups: new[]
            {
                new AppNetworkGroup(Guid.NewGuid(), "checkout-api", 5, 60, 0,
                    12, 20, 88, 140, 100, 0.12, AppNetworkLogic.VerdictNetworkBound, "network dominates"),
            });

        var doc = AppNetworkReportDocument.Build(report, "acme");
        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(doc));

        Assert.Contains("Network-bound", md);
        Assert.Contains("checkout-api", md);
    }

    [Fact]
    public void PerfPerCost_builder_maps_groups_and_missing_skus()
    {
        var report = new PerfPerCostReport(
            GeneratedAt: DateTime.UtcNow,
            CostTable: new CostTableInfo("2026-07", "Estimates only.", "shared/cloud-costs.json"),
            Formulas: new FormulasInfo("latency index formula", "mbps per dollar formula"),
            CompletedRuns: 10,
            ProvidersWithData: 2,
            Groups: new[]
            {
                new PerfPerCostGroup("azure", "B2s", "eastus", 0.0416m, "eastus", "http://x", "2026-07", null,
                    new[] { new PerfPerCostFamily("http", 3, 90, "latency_ms", 42.0, 88.0, "latency_cost_index", 561.0) }),
            },
            MissingCostSkus: new[] { new MissingCostSku("gcp", "e2-small", "us-central1") });

        var doc = PerfPerCostReportDocument.Build(report, "acme");
        var md = Encoding.UTF8.GetString(new MarkdownReportExporter().Render(doc));

        Assert.Contains("azure · B2s", md);
        Assert.Contains("SKUs missing from the price table", md);
        Assert.Contains("e2-small", md);
    }

    // ── helpers ────────────────────────────────────────────────────────────────

    private static AttemptView Attempt(
        int seq, string protocol, bool success, string? error = null, AttemptHttpView? http = null) =>
        new(Guid.NewGuid(), protocol, seq,
            new DateTime(2026, 7, 28, 14, 0, seq, DateTimeKind.Utc),
            new DateTime(2026, 7, 28, 14, 0, seq, DateTimeKind.Utc).AddMilliseconds(100),
            success, error, 0, Http: http);

    private static void WriteSmokeArtifact(IReportExporter exporter, byte[] bytes)
    {
        var dir = Environment.GetEnvironmentVariable("REPORT_SMOKE_DIR");
        if (string.IsNullOrWhiteSpace(dir))
        {
            return;
        }
        Directory.CreateDirectory(dir);
        File.WriteAllBytes(Path.Combine(dir, $"sample.{exporter.FileExtension}"), bytes);
    }
}
