using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Networker.ControlPlane.Auth;
using Networker.Data;

namespace Networker.ControlPlane.Endpoints;

/// <summary>
/// Phase-2 M5: PROJECT write endpoints — the C# port of the Rust
/// <c>crates/networker-dashboard/src/api/projects.rs</c> create / update /
/// delete handlers (M1 ported the reads in <see cref="ProjectsEndpoints"/>).
///
/// <para>Auth mapping: create + delete are platform-admin actions
/// (<see cref="AuthPolicies.GlobalAdmin"/>, mirroring the Rust
/// <c>is_platform_admin</c> gate); update requires project-admin on the routed
/// <c>{projectId}</c> (<see cref="AuthPolicies.ProjectAdmin"/>, mirroring
/// <c>require_project_role(ProjectRole::Admin)</c>).</para>
///
/// <para>Project IDs are generated by <see cref="ProjectIdGenerator"/> — a
/// faithful port of the Rust <c>project_id.rs</c> 14-char base36 format
/// (zone2 + ts6 + rand1 + server3 + 2 Damm check digits), using the same
/// <c>("us", "a20")</c> zone/server the Rust <c>db::projects::create_project</c>
/// hardcodes, so IDs from either backend validate interchangeably.</para>
///
/// <para>DELETE deviates from the legacy Rust handler by design (M5 spec): it
/// SOFT-deletes (sets <c>deleted_at</c>) and refuses protected projects; the
/// permanent cascade lives behind the admin hard-delete endpoint + the
/// inactivity lifecycle only.</para>
/// </summary>
public static class ProjectWriteEndpoints
{
    public static IEndpointRouteBuilder MapProjectWriteEndpoints(this IEndpointRouteBuilder app)
    {
        // POST /api/projects — create a project + creator admin membership
        // (Rust create_project). 201 with the full ProjectRow shape.
        app.MapPost("/api/projects", async (
            [FromBody] CreateProjectRequest req,
            HttpContext ctx,
            NetworkerDbContext db,
            CancellationToken ct) =>
        {
            var user = ctx.GetAuthUser();
            if (user is null)
            {
                return Results.Unauthorized();
            }

            if (string.IsNullOrWhiteSpace(req.Name))
            {
                return ApiError.BadRequest("Project name is required");
            }

            var slug = !string.IsNullOrWhiteSpace(req.Slug)
                ? req.Slug.Trim()
                : ProjectSlug.Slugify(req.Name);
            if (slug.Length == 0)
            {
                return ApiError.BadRequest("Project slug is required");
            }

            var now = DateTime.UtcNow;
            var project = new Data.Entities.Project
            {
                ProjectId = ProjectIdGenerator.Generate("us", "a20"),
                Name = req.Name.Trim(),
                Slug = slug,
                Description = req.Description,
                CreatedBy = user.UserId,
                CreatedAt = now,
                UpdatedAt = now,
                Settings = "{}",
                DeletedAt = null,
                DeleteProtection = false,
            };
            db.Projects.Add(project);

            // Creator becomes project admin (Rust parity).
            db.ProjectMembers.Add(new Data.Entities.ProjectMember
            {
                ProjectId = project.ProjectId,
                UserId = user.UserId,
                Role = "admin",
                Status = "active",
                JoinedAt = now,
                InvitedBy = user.UserId,
            });

            try
            {
                await db.SaveChangesAsync(ct);
            }
            catch (DbUpdateException ex) when (IsUniqueViolation(ex))
            {
                // UNIQUE(slug) → 409 so the frontend can prompt for another.
                return ApiError.Conflict("a project with this slug already exists");
            }

            return Results.Created($"/api/projects/{project.ProjectId}", ToDto(project));
        }).RequireAuthorization(AuthPolicies.GlobalAdmin);

        // PUT /api/projects/{projectId} — update name / description / settings
        // (Rust update_project_detail; absent fields keep their current value).
        app.MapPut("/api/projects/{projectId}", async (
            string projectId,
            [FromBody] UpdateProjectRequest req,
            NetworkerDbContext db,
            CancellationToken ct) =>
        {
            var project = await db.Projects.FirstOrDefaultAsync(p => p.ProjectId == projectId, ct);
            if (project is null)
            {
                return Results.NotFound();
            }

            if (!string.IsNullOrWhiteSpace(req.Name))
            {
                project.Name = req.Name.Trim();
            }
            if (req.Description is not null)
            {
                project.Description = req.Description;
            }
            if (req.Settings is { ValueKind: not JsonValueKind.Undefined and not JsonValueKind.Null } settings)
            {
                project.Settings = settings.GetRawText();
            }

            project.UpdatedAt = DateTime.UtcNow;
            await db.SaveChangesAsync(ct);

            return Results.Ok(new { success = true });
        }).RequireAuthorization(AuthPolicies.ProjectAdmin);

        // DELETE /api/projects/{projectId} — SOFT delete (set deleted_at);
        // refused while delete_protection is on. Platform-admin only.
        app.MapDelete("/api/projects/{projectId}", async (
            string projectId,
            HttpContext ctx,
            NetworkerDbContext db,
            ILoggerFactory lf,
            CancellationToken ct) =>
        {
            var project = await db.Projects.FirstOrDefaultAsync(p => p.ProjectId == projectId, ct);
            if (project is null)
            {
                return Results.NotFound();
            }
            if (project.DeleteProtection)
            {
                return ApiError.BadRequest("Project has delete protection enabled");
            }

            if (project.DeletedAt is null)
            {
                project.DeletedAt = DateTime.UtcNow;
                await db.SaveChangesAsync(ct);
            }

            lf.CreateLogger("ProjectWriteEndpoints").LogInformation(
                "Project {ProjectId} soft-deleted by {Admin}",
                projectId, ctx.GetAuthUser()?.Email);
            return Results.Ok(new { success = true });
        }).RequireAuthorization(AuthPolicies.GlobalAdmin);

        return app;
    }

    // ── DTOs ──────────────────────────────────────────────────────────────────

    /// <summary>POST /api/projects body — mirrors Rust <c>CreateProjectRequest</c>.</summary>
    public sealed record CreateProjectRequest(
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("description")] string? Description,
        [property: JsonPropertyName("slug")] string? Slug);

    /// <summary>PUT /api/projects/{projectId} body — mirrors Rust <c>UpdateProjectRequest</c>.</summary>
    public sealed record UpdateProjectRequest(
        [property: JsonPropertyName("name")] string? Name,
        [property: JsonPropertyName("description")] string? Description,
        [property: JsonPropertyName("settings")] JsonElement? Settings);

    /// <summary>Full project row — matches the Rust <c>ProjectRow</c> serde shape.</summary>
    private static object ToDto(Data.Entities.Project p) => new
    {
        project_id = p.ProjectId,
        name = p.Name,
        slug = p.Slug,
        description = p.Description,
        created_by = p.CreatedBy,
        created_at = p.CreatedAt,
        updated_at = p.UpdatedAt,
        settings = JsonDocument.Parse(
            string.IsNullOrWhiteSpace(p.Settings) ? "{}" : p.Settings).RootElement.Clone(),
        deleted_at = p.DeletedAt,
        delete_protection = p.DeleteProtection,
    };

    private static bool IsUniqueViolation(DbUpdateException ex)
        => ex.InnerException is PostgresException { SqlState: PostgresErrorCodes.UniqueViolation };
}

/// <summary>
/// Port of the Rust <c>db::projects::slugify</c>: lowercase, spaces → hyphens,
/// strip everything but ASCII alphanumerics and hyphens, collapse runs of
/// hyphens, trim leading/trailing hyphens.
/// </summary>
public static class ProjectSlug
{
    public static string Slugify(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name.ToLowerInvariant())
        {
            if (c is (>= 'a' and <= 'z') or (>= '0' and <= '9') or '-')
            {
                sb.Append(c);
            }
            else if (c == ' ')
            {
                sb.Append('-');
            }
            // everything else: strip
        }

        return string.Join('-',
            sb.ToString().Split('-', StringSplitOptions.RemoveEmptyEntries));
    }
}

/// <summary>
/// Port of the Rust <c>project_id.rs</c> ProjectId generator: a 14-character
/// lowercase base36 identifier laid out as <c>ZZ TTTTTT R SSS KK</c> —
/// 2 zone chars, 6 timestamp chars (seconds since 2026-01-01T00:00:00Z),
/// 1 random char, 3 server-id chars, and 2 Damm check digits (double-pass over
/// affine Latin squares M=3 and M=5 in Z_36, exactly the Rust tables), so IDs
/// minted here pass the Rust <c>ProjectId::validate</c> and vice versa.
/// </summary>
public static class ProjectIdGenerator
{
    /// <summary>Seconds from Unix epoch to the project epoch (2026-01-01T00:00:00Z).</summary>
    public const long ProjectEpoch = 1_767_225_600;

    private const string Alphabet = "0123456789abcdefghijklmnopqrstuvwxyz";

    /// <summary>Generate an id for the current time.</summary>
    public static string Generate(string zone, string serverId)
        => GenerateDeterministic(zone, serverId, DateTimeOffset.UtcNow.ToUnixTimeSeconds(),
            RandomNumberGenerator.GetInt32(36));

    /// <summary>
    /// Deterministic variant (testable): explicit Unix seconds + random digit
    /// (0..35). Mirrors Rust <c>ProjectId::generate_deterministic</c>.
    /// </summary>
    public static string GenerateDeterministic(string zone, string serverId, long unixSecs, int randomDigit)
    {
        ArgumentOutOfRangeException.ThrowIfNotEqual(zone.Length, 2, nameof(zone));
        ArgumentOutOfRangeException.ThrowIfNotEqual(serverId.Length, 3, nameof(serverId));
        ArgumentOutOfRangeException.ThrowIfNegative(randomDigit);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(randomDigit, 36);
        if (!IsBase36(zone) || !IsBase36(serverId))
        {
            throw new ArgumentException("zone and serverId must be lowercase base36");
        }

        var elapsed = Math.Max(unixSecs - ProjectEpoch, 0);
        var ts = EncodeBase36((ulong)elapsed, 6);
        var raw = $"{zone}{ts}{Alphabet[randomDigit]}{serverId}";
        return raw + DammBase36Double(raw);
    }

    /// <summary>Validate a well-formed id: 14 lowercase base36 chars with valid
    /// double Damm check digits (mirrors Rust <c>ProjectId::validate</c>).</summary>
    public static bool Validate(string? id)
        => id is { Length: 14 } && IsBase36(id)
           && VerifyDammBase36Double(id[..12], id[12..]);

    /// <summary>Base36-encode <paramref name="val"/> zero-padded to <paramref name="width"/>.</summary>
    public static string EncodeBase36(ulong val, int width)
    {
        Span<char> digits = stackalloc char[width];
        var v = val;
        for (var i = width - 1; i >= 0; i--)
        {
            digits[i] = Alphabet[(int)(v % 36)];
            v /= 36;
        }
        return new string(digits);
    }

    private static bool IsBase36(string s)
        => s.All(c => c is (>= '0' and <= '9') or (>= 'a' and <= 'z'));

    private static int CharToDigit(char c) => c switch
    {
        >= '0' and <= '9' => c - '0',
        >= 'a' and <= 'z' => c - 'a' + 10,
        _ => -1,
    };

    /// <summary>table[r][c] = (m*r + c) % 36 — the Rust affine Damm tables (m=3, m=5).</summary>
    private static int DammStep(int m, int interim, int digit) => (m * interim + digit) % 36;

    private static int? DammPass(string s, int m)
    {
        var interim = 0;
        foreach (var c in s)
        {
            var d = CharToDigit(c);
            if (d < 0)
            {
                return null;
            }
            interim = DammStep(m, interim, d);
        }
        return interim;
    }

    /// <summary>Find the check digit k with table[interim][k] == 0, i.e.
    /// (m*interim + k) % 36 == 0.</summary>
    private static int ZeroingDigit(int m, int interim) => (36 - (m * interim) % 36) % 36;

    /// <summary>Two Damm check chars for <paramref name="raw"/> — pass 1 (m=3)
    /// over raw → c1; pass 2 (m=5) over raw+c1 → c2 (Rust <c>damm_base36_double</c>).</summary>
    public static string DammBase36Double(string raw)
    {
        var interim1 = DammPass(raw, 3)
            ?? throw new ArgumentException("raw must be valid base36", nameof(raw));
        var c1 = ZeroingDigit(3, interim1);

        var interim2 = DammPass(raw + Alphabet[c1], 5)!.Value;
        var c2 = ZeroingDigit(5, interim2);

        return $"{Alphabet[c1]}{Alphabet[c2]}";
    }

    /// <summary>Verify the two-char <paramref name="check"/> for <paramref name="raw"/>
    /// (Rust <c>verify_damm_base36_double</c>).</summary>
    public static bool VerifyDammBase36Double(string raw, string check)
    {
        if (check.Length != 2)
        {
            return false;
        }

        var c1 = CharToDigit(check[0]);
        var c2 = CharToDigit(check[1]);
        if (c1 < 0 || c2 < 0)
        {
            return false;
        }

        var interim1 = DammPass(raw, 3);
        if (interim1 is null || DammStep(3, interim1.Value, c1) != 0)
        {
            return false;
        }

        var interim2 = DammPass(raw + check[0], 5);
        return interim2 is not null && DammStep(5, interim2.Value, c2) == 0;
    }
}
